//! # MAL Backend (Phase 62)
//!
//! Transpiles NIR to C, then uses GCC to produce native binaries.
//! This is the "cfront approach" used by early C++, Vala, and many
//! educational compilers.
//!
//! Mathematical Foundation:
//!   NIR → C99 → GCC → ELF binary
//!   Compilation is a homomorphism: ⟦compile(p)⟧ = ⟦p⟧
//!
//! Honest Caveat (Principle 5):
//!   - This is a TRANSLATOR, not an optimizer
//!   - No LLVM JIT, no dynamic compilation
#![forbid(unsafe_code)]
use std::fmt::Write;
use std::fs;
use std::process::Command;
use std::sync::atomic::{AtomicU64, Ordering};
use std::thread;
use std::time::{Duration, SystemTime};
// ═══════════════════════════════════════════════════════════
// TYPE MAPPING
// ═══════════════════════════════════════════════════════════
pub fn c_type(mal_type: &str) -> &'static str {
    match mal_type {
        "i64" | "int" => "int64_t",
        "i32" => "int32_t",
        "i16" => "int16_t",
        "i8" => "int8_t",
        "u64" => "uint64_t",
        "u32" => "uint32_t",
        "u16" => "uint16_t",
        "u8" => "uint8_t",
        "f64" | "float" => "double",
        "f32" => "float",
        "bool" => "bool",
        "string" | "str" => "const char*",
        "void" | "unit" => "void",
        _ => "int64_t",
    }
}
// ═══════════════════════════════════════════════════════════
// C GENERATOR
// ═══════════════════════════════════════════════════════════
#[derive(Debug, Default)]
pub struct CFunction {
    pub name: String,
    pub return_type: String,
    pub params: Vec<(String, String)>,
    pub body: Vec<String>,
    pub locals: Vec<(String, String)>,
}
impl CFunction {
    pub fn new(name: impl Into<String>, ret: impl Into<String>) -> Self {
        Self { name: name.into(), return_type: ret.into(), ..Default::default() }
    }
    pub fn add_param(&mut self, name: impl Into<String>, typ: impl Into<String>) {
        self.params.push((name.into(), typ.into()));
    }
    pub fn add_local(&mut self, name: impl Into<String>, typ: impl Into<String>) {
        self.locals.push((name.into(), typ.into()));
    }
    pub fn add_stmt(&mut self, stmt: impl Into<String>) {
        self.body.push(stmt.into());
    }
    pub fn render(&self) -> String {
        let mut out = String::new();
        let params = if self.params.is_empty() {
            "void".to_string()
        } else {
            self.params.iter()
                .map(|(n, t)| format!("{} {}", c_type(t), n))
                .collect::<Vec<_>>()
                .join(", ")
        };
        writeln!(out, "{} {}({}) {{", c_type(&self.return_type), self.name, params).unwrap();
        for (n, t) in &self.locals {
            writeln!(out, "    {} {};", c_type(t), n).unwrap();
        }
        for stmt in &self.body {
            writeln!(out, "    {}", stmt).unwrap();
        }
        writeln!(out, "}}").unwrap();
        out
    }
}
#[derive(Debug, Default)]
pub struct CTranslationUnit {
    pub includes: Vec<String>,
    pub functions: Vec<CFunction>,
}
impl CTranslationUnit {
    pub fn new() -> Self {
        let mut tu = Self::default();
        tu.includes.push("#include <stdint.h>".into());
        tu.includes.push("#include <stdbool.h>".into());
        tu.includes.push("#include <stdio.h>".into());
        tu.includes.push("#include <stdlib.h>".into());
        tu.includes.push("#include <string.h>".into());
        tu
    }
    pub fn add_function(&mut self, func: CFunction) {
        self.functions.push(func);
    }
    pub fn render(&self) -> String {
        let mut out = String::new();
        writeln!(out, "/* Generated by MAL Backend (Phase 62)").unwrap();
        writeln!(out, " * Transpiled from MAL NIR to C99").unwrap();
        writeln!(out, " * Constitutional Compliance: Principle 5 (Honesty)").unwrap();
        writeln!(out, " */\n").unwrap();
        for inc in &self.includes {
            writeln!(out, "{}", inc).unwrap();
        }
        writeln!(out).unwrap();
        for func in &self.functions {
            out.push_str(&func.render());
            writeln!(out).unwrap();
        }
        out
    }
}
// ═══════════════════════════════════════════════════════════
// COMPILATION
// ═══════════════════════════════════════════════════════════
#[derive(Debug, Clone)]
pub struct CompileOptions {
    pub optimize: bool,
    pub output_name: String,
    pub keep_c_source: bool,
}
impl Default for CompileOptions {
    fn default() -> Self {
        Self { optimize: true, output_name: "a.out".into(), keep_c_source: false }
    }
}
#[derive(Debug)]
pub struct CompilationResult {
    pub success: bool,
    pub c_source: String,
    pub binary_path: Option<String>,
    pub errors: Vec<String>,
    pub warnings: Vec<String>,
}
pub fn transpile_to_c(program: &str) -> Result<CTranslationUnit, String> {
    let mut tu = CTranslationUnit::new();
    let lines: Vec<&str> = program.lines().collect();
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i].trim();
        if line.starts_with("fn ") {
            let (func, consumed) = parse_function(&lines[i..])?;
            tu.add_function(func);
            i += consumed;
        } else {
            i += 1;
        }
    }
    Ok(tu)
}
fn parse_function(lines: &[&str]) -> Result<(CFunction, usize), String> {
    let first = lines[0].trim();
    let name_end = first.find('(').ok_or("Invalid function")?;
    let name = first[3..name_end].trim();
    let params_start = name_end + 1;
    let params_end = first.find(')').ok_or("Invalid function")?;
    let params_str = &first[params_start..params_end];
    let ret_start = first.find("->").map(|p| p + 2).unwrap_or(params_end);
    let ret_end = first.find('{').ok_or("Invalid function")?;
    let ret_type = first[ret_start..ret_end].trim();
    let mut func = CFunction::new(name, if ret_type.is_empty() { "void" } else { ret_type });
    if !params_str.trim().is_empty() {
        for param in params_str.split(',') {
            let param = param.trim();
            if let Some(colon) = param.find(':') {
                func.add_param(param[..colon].trim(), param[colon+1..].trim());
            }
        }
    }
    let mut i = 1;
    let mut depth = 1;
    while i < lines.len() && depth > 0 {
        let line = lines[i].trim();
        if line == "}" {
            depth -= 1;
            if depth == 0 { i += 1; break; }
        } else if line.ends_with('{') {
            depth += 1;
        }
        if let Some(c_stmt) = translate_statement(line) {
            func.add_stmt(c_stmt);
        }
        i += 1;
    }
    Ok((func, i))
}
fn translate_statement(nir: &str) -> Option<String> {
    let nir = nir.trim();
    if nir.is_empty() { return None; }
    if nir.starts_with("let ") {
        let rest = &nir[4..].trim_end_matches(';');
        if let (Some(colon), Some(eq)) = (rest.find(':'), rest.find('=')) {
            let name = rest[..colon].trim();
            let typ = rest[colon+1..eq].trim();
            let expr = rest[eq+1..].trim();
            return Some(format!("{} {} = {};", c_type(typ), name, translate_expr(expr)));
        }
    }
    if nir.starts_with("return ") {
        let expr = nir[7..].trim().trim_end_matches(';');
        return Some(format!("return {};", translate_expr(expr)));
    }
    if nir.starts_with("print") { return Some(nir.to_string()); }
    if !nir.ends_with(';') { Some(format!("{};", nir)) } else { Some(nir.to_string()) }
}
fn translate_expr(expr: &str) -> String {
    expr.to_string()
}
pub fn compile_c_to_binary(c_source: &str, options: &CompileOptions) -> CompilationResult {
    // Injective file naming: pid + nanos + counter
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let unique_id = format!(
        "{}_{}_{}",
        std::process::id(),
        SystemTime::now().duration_since(SystemTime::UNIX_EPOCH).unwrap_or_default().as_nanos(),
        COUNTER.fetch_add(1, Ordering::SeqCst)
    );
    let c_file = format!("/tmp/mal_{}.c", unique_id);
    let binary_path = format!("/tmp/mal_bin_{}", unique_id);
    if let Err(e) = fs::write(&c_file, c_source) {
        return CompilationResult {
            success: false, c_source: c_source.into(), binary_path: None,
            errors: vec![format!("Write failed: {}", e)], warnings: vec![],
        };
    }
    let mut cmd = Command::new("gcc");
    cmd.arg(&c_file).arg("-o").arg(&binary_path).arg("-Wall").arg("-Wextra");
    if options.optimize { cmd.arg("-O2"); }
    let output = match cmd.output() {
        Ok(o) => o,
        Err(e) => {
            let _ = fs::remove_file(&c_file);
            return CompilationResult {
                success: false, c_source: c_source.into(), binary_path: None,
                errors: vec![format!("GCC failed: {}", e)], warnings: vec![],
            };
        }
    };
    if !options.keep_c_source { let _ = fs::remove_file(&c_file); }
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();
    if output.status.success() {
        let warnings = stderr.lines().filter(|l| l.contains("warning")).map(String::from).collect();
        CompilationResult {
            success: true, c_source: c_source.into(), binary_path: Some(binary_path),
            errors: vec![], warnings,
        }
    } else {
        CompilationResult {
            success: false, c_source: c_source.into(), binary_path: None,
            errors: vec![stderr], warnings: vec![],
        }
    }
}
pub fn run_binary(binary_path: &str, args: &[&str]) -> Result<String, String> {
    // 50ms delay to ensure filesystem sync
    thread::sleep(Duration::from_millis(50));
    let output = Command::new(binary_path).args(args).output()
        .map_err(|e| format!("Run failed: {}", e))?;
    let stdout = String::from_utf8_lossy(&output.stdout).to_string();
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();
    if output.status.success() {
        Ok(stdout)
    } else {
        Err(format!("Exit {:?}\nstderr: {}", output.status.code(), stderr))
    }
}
// ═══════════════════════════════════════════════════════════
// TESTS
// ═══════════════════════════════════════════════════════════
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_hello_world() {
        let nir = r#"
fn main() -> i32 {
    printf("أهلاً بالعالم\n");
    return 0;
}
"#;
        let tu = transpile_to_c(nir).expect("transpile failed");
        let c_source = tu.render();
        assert!(c_source.contains("#include <stdio.h>"));
        assert!(c_source.contains("int32_t main"));
        let opts = CompileOptions::default();
        let result = compile_c_to_binary(&c_source, &opts);
        assert!(result.success, "Errors: {:?}", result.errors);
        let output = run_binary(result.binary_path.as_ref().unwrap(), &[]).unwrap();
        assert!(output.contains("أهلاً بالعالم"));
    }
    #[test]
    fn test_addition_function() {
        let nir = r#"
fn add(a: i32, b: i32) -> i32 {
    return a + b;
}
fn main() -> i32 {
    printf("%d\n", add(17, 25));
    return 0;
}
"#;
        let tu = transpile_to_c(nir).expect("transpile failed");
        let c_source = tu.render();
        assert!(c_source.contains("int32_t add(int32_t a, int32_t b)"));
        let opts = CompileOptions::default();
        let result = compile_c_to_binary(&c_source, &opts);
        assert!(result.success, "Errors: {:?}", result.errors);
        let output = run_binary(result.binary_path.as_ref().unwrap(), &[]).unwrap();
        assert_eq!(output.trim(), "42");
    }
    #[test]
    fn test_fibonacci() {
        let nir = r#"
fn fib(n: i32) -> i32 {
    if (n <= 1) return n;
    return fib(n-1) + fib(n-2);
}
fn main() -> i32 {
    printf("fib(10) = %d\n", fib(10));
    return 0;
}
"#;
        let tu = transpile_to_c(nir).expect("transpile failed");
        let c_source = tu.render();
        assert!(c_source.contains("int32_t fib(int32_t n)"));
        let opts = CompileOptions { optimize: true, ..Default::default() };
        let result = compile_c_to_binary(&c_source, &opts);
        assert!(result.success, "Errors: {:?}", result.errors);
        let output = run_binary(result.binary_path.as_ref().unwrap(), &[]).unwrap();
        assert!(output.contains("fib(10) = 55"));
    }
    #[test]
    fn test_type_mapping() {
        assert_eq!(c_type("i32"), "int32_t");
        assert_eq!(c_type("i64"), "int64_t");
        assert_eq!(c_type("u8"), "uint8_t");
        assert_eq!(c_type("f64"), "double");
        assert_eq!(c_type("bool"), "bool");
        assert_eq!(c_type("string"), "const char*");
        assert_eq!(c_type("void"), "void");
        assert_eq!(c_type("unknown_type"), "int64_t");
    }
    #[test]
    fn test_abjad_integration() {
        let nir = r#"
fn abjad_mim() -> i32 {
    return 40;
}
fn abjad_ha() -> i32 {
    return 8;
}
fn abjad_dal() -> i32 {
    return 4;
}
fn main() -> i32 {
    int sum = abjad_mim() + abjad_ha() + abjad_mim() + abjad_dal();
    printf("محمد = %d\n", sum);
    return 0;
}
"#;
        let tu = transpile_to_c(nir).expect("transpile failed");
        let c_source = tu.render();
        let opts = CompileOptions::default();
        let result = compile_c_to_binary(&c_source, &opts);
        assert!(result.success, "Errors: {:?}", result.errors);
        let output = run_binary(result.binary_path.as_ref().unwrap(), &[]).unwrap();
        assert!(output.contains("محمد = 92"), "Got: {}", output);
    }
}
