[package]
name = "mal_native"
version = "0.1.0"
edition = "2021"
description = "MAL Native Compiler — AOT to x86-64 without libc"
license = "MIT"
[lib]
path = "src/lib.rs"
crate-type = ["lib"]
[dependencies]
mal_nir = { path = "../nir" }
tempfile = "3.8"
[dev-dependencies]
mal_parser = { path = "../parser" }
