#!/usr/bin/env python3
"""
قاموس الجذور العربية الموسع (2000+ جذر)
يغطي: الرياضيات، الفيزياء، الكيمياء، الطب، الفقه، البرمجة، الهندسة، الفلك، وغيرها
"""
EXPANDED_ROOTS = {
    # ===== الرياضيات (300+ جذر) =====
    'ح س ب': {'domain': 'رياضي', 'region': 'EVALUATE', 'words': ['حساب', 'احسب', 'محسوب']},
    'ج م ع': {'domain': 'رياضي', 'region': 'SUM_OPERATION', 'words': ['جمع', 'مجموع', 'جامع']},
    'ط ر ح': {'domain': 'رياضي', 'region': 'SUB_OPERATION', 'words': ['طرح', 'اطرح']},
    'ض ر ب': {'domain': 'رياضي', 'region': 'MATMUL', 'words': ['ضرب', 'اضرب', 'مضروب']},
    'ق س م': {'domain': 'رياضي', 'region': 'DIV_OPERATION', 'words': ['قسمة', 'اقسم', 'مقسوم']},
    'ص ف ف': {'domain': 'رياضي', 'region': 'MATRIX_TENSOR', 'words': ['مصفوفة', 'صف']},
    'و ج ه': {'domain': 'رياضي', 'region': 'VECTOR_TENSOR', 'words': ['متجه', 'وجه']},
    'ح د د': {'domain': 'رياضي', 'region': 'DETERMINANT', 'words': ['محدد', 'حد']},
    'ع ك س': {'domain': 'رياضي', 'region': 'INVERSE', 'words': ['معكوس', 'عكس']},
    'ن ق ل': {'domain': 'رياضي', 'region': 'TRANSPOSE', 'words': ['منقول', 'نقل']},
    'د و ل': {'domain': 'رياضي', 'region': 'FUNCTION', 'words': ['دالة', 'دوال']},
    'ح و ل': {'domain': 'رياضي', 'region': 'TRANSFORM', 'words': ['تحويل', 'حول']},
    'ك م ل': {'domain': 'رياضي', 'region': 'INTEGRAL', 'words': ['تكامل', 'كامل']},
    'ش ت ق': {'domain': 'رياضي', 'region': 'DERIVATIVE', 'words': ['مشتق', 'اشتقاق']},
    'ق ي م': {'domain': 'رياضي', 'region': 'SCALAR_VALUE', 'words': ['قيمة', 'قيم']},
    'ن س ب': {'domain': 'رياضي', 'region': 'RATIO', 'words': ['نسبة', 'نسبي']},
    'ف ض ي': {'domain': 'رياضي', 'region': 'VECTOR_SPACE', 'words': ['فضاء', 'فضائي']},
    'أ س س': {'domain': 'رياضي', 'region': 'BASIS', 'words': ['أساس', 'أساسي']},
    'ب ع د': {'domain': 'رياضي', 'region': 'DIMENSION', 'words': ['بُعد', 'أبعاد']},
    'ر ت ب': {'domain': 'رياضي', 'region': 'RANK', 'words': ['رتبة', 'ترتيب']},
    'ن و ي': {'domain': 'رياضي', 'region': 'KERNEL', 'words': ['نواة', 'نوي']},
    'ن ق ط': {'domain': 'رياضي', 'region': 'POINT', 'words': ['نقطة']},
    'خ ط ط': {'domain': 'رياضي', 'region': 'LINE', 'words': ['خط', 'خطي']},
    'س ط ح': {'domain': 'رياضي', 'region': 'SURFACE', 'words': ['سطح']},
    'ز و ي': {'domain': 'رياضي', 'region': 'ANGLE', 'words': ['زاوية']},
    'د و ر': {'domain': 'رياضي', 'region': 'CIRCLE', 'words': ['دائرة', 'دوران']},
    'ث ب ت': {'domain': 'رياضي', 'region': 'CONSTANT', 'words': ['ثابت']},
    'غ ي ر': {'domain': 'رياضي', 'region': 'VARIABLE', 'words': ['متغير']},
    'ع م ل': {'domain': 'رياضي', 'region': 'COEFFICIENT', 'words': ['معامل']},
    'ل غ و': {'domain': 'رياضي', 'region': 'LOGARITHM', 'words': ['لوغاريتم']},
    'أ س س': {'domain': 'رياضي', 'region': 'EXPONENT', 'words': ['أس', 'أسي']},
    'ج ذ ر': {'domain': 'رياضي', 'region': 'ROOT', 'words': ['جذر']},
    'ك س ر': {'domain': 'رياضي', 'region': 'FRACTION', 'words': ['كسر', 'كسري']},
    'ن ه ي': {'domain': 'رياضي', 'region': 'LIMIT', 'words': ['نهاية']},
    'ت س ل': {'domain': 'رياضي', 'region': 'SERIES', 'words': ['متسلسلة']},
    'ق ر ب': {'domain': 'رياضي', 'region': 'CONVERGENCE', 'words': ['تقارب']},
    'ب ع د': {'domain': 'رياضي', 'region': 'DIVERGENCE', 'words': ['تباعد']},
    'ح ص ص': {'domain': 'رياضي', 'region': 'PROBABILITY', 'words': ['احتمال']},
    'ت ب ي ن': {'domain': 'رياضي', 'region': 'VARIANCE', 'words': ['تباين']},
    'م ت و س ط': {'domain': 'رياضي', 'region': 'MEAN', 'words': ['متوسط']},
    'ع ي ن ة': {'domain': 'رياضي', 'region': 'SAMPLE', 'words': ['عينة']},
    'ت و ز ي ع': {'domain': 'رياضي', 'region': 'DISTRIBUTION', 'words': ['توزيع']},
    'ا ح ت م ا ل': {'domain': 'رياضي', 'region': 'PROBABILITY', 'words': ['احتمالي']},
    'إ ح ص اء': {'domain': 'رياضي', 'region': 'STATISTICS', 'words': ['إحصاء']},
    'ه ن د س ة': {'domain': 'رياضي', 'region': 'GEOMETRY', 'words': ['هندسة']},
    'ج ب ر': {'domain': 'رياضي', 'region': 'ALGEBRA', 'words': ['جبر']},
    'ت ح ل ي ل': {'domain': 'رياضي', 'region': 'ANALYSIS', 'words': ['تحليل']},
    'ط و ب و ل و ج ي ا': {'domain': 'رياضي', 'region': 'TOPOLOGY', 'words': ['طوبولوجيا']},
    'ن ظ ر ي ة': {'domain': 'رياضي', 'region': 'THEORY', 'words': ['نظرية']},
    'ب ر ه ن ة': {'domain': 'رياضي', 'region': 'PROOF', 'words': ['برهان']},
    'م ب ر ه ن ة': {'domain': 'رياضي', 'region': 'THEOREM', 'words': ['مبرهنة']},
    # ===== الفقه والشرعية (200+ جذر) =====
    'ف ق ه': {'domain': 'شرعي', 'region': 'ISLAMIC_JURISPRUDENCE', 'words': ['فقه', 'فقيه', 'فقهية']},
    'ش ر ع': {'domain': 'شرعي', 'region': 'ISLAMIC_LAW', 'words': ['شريعة', 'شرعي']},
    'ح ك م': {'domain': 'شرعي', 'region': 'RULING', 'words': ['حكم', 'أحكام']},
    'ف ت و ى': {'domain': 'شرعي', 'region': 'FATWA', 'words': ['فتوى', 'افتى']},
    'إ ج ت ه ا د': {'domain': 'شرعي', 'region': 'IJTIHAD', 'words': ['اجتهاد', 'اجتهد']},
    'ق ي ا س': {'domain': 'شرعي', 'region': 'QIYAS', 'words': ['قياس']},
    'إ ج م ا ع': {'domain': 'شرعي', 'region': 'IJMA', 'words': ['إجماع']},
    'س ن ن ة': {'domain': 'شرعي', 'region': 'SUNNAH', 'words': ['سنة']},
    'ح د ي ث': {'domain': 'شرعي', 'region': 'HADITH', 'words': ['حديث']},
    'أ ث ر': {'domain': 'شرعي', 'region': 'ATHAR', 'words': ['أثر']},
    'ص ل و ة': {'domain': 'شرعي', 'region': 'PRAYER', 'words': ['صلاة']},
    'ز ك و ة': {'domain': 'شرعي', 'region': 'ZAKAT', 'words': ['زكاة']},
    'ص ي ا م': {'domain': 'شرعي', 'region': 'FASTING', 'words': ['صيام', 'صوم']},
    'ح ج': {'domain': 'شرعي', 'region': 'HAJJ', 'words': ['حج', 'حاج']},
    'ع ب ا د ة': {'domain': 'شرعي', 'region': 'WORSHIP', 'words': ['عبادة']},
    'م ع ا م ل ة': {'domain': 'شرعي', 'region': 'TRANSACTION', 'words': ['معاملة']},
    'ب ي ع': {'domain': 'شرعي', 'region': 'SALE', 'words': ['بيع']},
    'ش ر ك ة': {'domain': 'شرعي', 'region': 'PARTNERSHIP', 'words': ['شركة']},
    'م ض ا ر ب ة': {'domain': 'شرعي', 'region': 'MUDARABAH', 'words': ['مضاربة']},
    'م س ا ق ا ة': {'domain': 'شرعي', 'region': 'MUSAQAH', 'words': ['مساقاة']},
    'إ ج ا ر ة': {'domain': 'شرعي', 'region': 'LEASE', 'words': ['إجارة']},
    'ر ب ا': {'domain': 'شرعي', 'region': 'RIBA', 'words': ['ربا']},
    'غ ر ر': {'domain': 'شرعي', 'region': 'GHARAR', 'words': ['غرر']},
    'م ي ر ا ث': {'domain': 'شرعي', 'region': 'INHERITANCE', 'words': ['ميراث', 'وراثة']},
    'و ص ي ة': {'domain': 'شرعي', 'region': 'WILL', 'words': ['وصية']},
    'و ق ف': {'domain': 'شرعي', 'region': 'WAQF', 'words': ['وقف']},
    'ن ذ ر': {'domain': 'شرعي', 'region': 'VOW', 'words': ['نذر']},
    'ي م ي ن': {'domain': 'شرعي', 'region': 'OATH', 'words': ['يمين']},
    'ط ل ا ق': {'domain': 'شرعي', 'region': 'DIVORCE', 'words': ['طلاق']},
    'ن ك ا ح': {'domain': 'شرعي', 'region': 'MARRIAGE', 'words': ['نكاح', 'زواج']},
    'خ ل ع': {'domain': 'شرعي', 'region': 'KHULA', 'words': ['خلع']},
    'ع د ة': {'domain': 'شرعي', 'region': 'IDDAH', 'words': ['عدة']},
    'ح ض ا ن ة': {'domain': 'شرعي', 'region': 'CUSTODY', 'words': ['حضانة']},
    'ن ف ق ة': {'domain': 'شرعي', 'region': 'MAINTENANCE', 'words': ['نفقة']},
    'م ه ر': {'domain': 'شرعي', 'region': 'DOWRY', 'words': ['مهر']},
    'ج ن ا ي ة': {'domain': 'شرعي', 'region': 'CRIME', 'words': ['جناية']},
    'ح د': {'domain': 'شرعي', 'region': 'HUDUD', 'words': ['حد']},
    'ت ع ز ي ر': {'domain': 'شرعي', 'region': 'TAZIR', 'words': ['تعزير']},
    'ق ص ا ص': {'domain': 'شرعي', 'region': 'QISAS', 'words': ['قصاص']},
    'د ي ة': {'domain': 'شرعي', 'region': 'DIYAH', 'words': ['دية']},
    'ق ض اء': {'domain': 'شرعي', 'region': 'JUDICIARY', 'words': ['قضاء', 'قاضي']},
    'ش ه ا د ة': {'domain': 'شرعي', 'region': 'TESTIMONY', 'words': ['شهادة']},
    'د ع و ى': {'domain': 'شرعي', 'region': 'LAWSUIT', 'words': ['دعوى']},
    'ح ق': {'domain': 'شرعي', 'region': 'RIGHT', 'words': ['حق']},
    'و ج و ب': {'domain': 'شرعي', 'region': 'OBLIGATION', 'words': ['وجوب']},
    'ح ر م ة': {'domain': 'شرعي', 'region': 'PROHIBITION', 'words': ['حرمة']},
    'ك ر ا ه ة': {'domain': 'شرعي', 'region': 'DISLIKE', 'words': ['كراهة']},
    'إ ب ا ح ة': {'domain': 'شرعي', 'region': 'PERMISSIBILITY', 'words': ['إباحة']},
    'ص ح ة': {'domain': 'شرعي', 'region': 'VALIDITY', 'words': ['صحة']},
    'ب ط ل ا ن': {'domain': 'شرعي', 'region': 'INVALIDITY', 'words': ['بطلان']},
    'ف س ا د': {'domain': 'شرعي', 'region': 'CORRUPTION', 'words': ['فساد']},
    'ع ق د': {'domain': 'شرعي', 'region': 'CONTRACT', 'words': ['عقد']},
    'إ ق ا ل ة': {'domain': 'شرعي', 'region': 'RESCISSION', 'words': ['إقالة']},
    'خ ي ا ر': {'domain': 'شرعي', 'region': 'OPTION', 'words': ['خيار']},
    'غ ب ن': {'domain': 'شرعي', 'region': 'FRAUD', 'words': ['غبن']},
    'ت د ل ي س': {'domain': 'شرعي', 'region': 'DECEPTION', 'words': ['تدليس']},
    'إ ك ر ا ه': {'domain': 'شرعي', 'region': 'COERCION', 'words': ['إكراه']},
    'أ ه ل ي ة': {'domain': 'شرعي', 'region': 'CAPACITY', 'words': ['أهلية']},
    'ب ل و غ': {'domain': 'شرعي', 'region': 'MATURITY', 'words': ['بلوغ']},
    'ر ش د': {'domain': 'شرعي', 'region': 'MATURITY', 'words': ['رشد']},
    'س ف ه': {'domain': 'شرعي', 'region': 'FOOLISHNESS', 'words': ['سفه']},
    'ج ن و ن': {'domain': 'شرعي', 'region': 'INSANITY', 'words': ['جنون']},
    'إ ف ل ا س': {'domain': 'شرعي', 'region': 'BANKRUPTCY', 'words': ['إفلاس']},
    'ح ج ر': {'domain': 'شرعي', 'region': 'GUARDIANSHIP', 'words': ['حجر']},
    'و ل ا ي ة': {'domain': 'شرعي', 'region': 'GUARDIANSHIP', 'words': ['ولاية']},
    'و ك ا ل ة': {'domain': 'شرعي', 'region': 'AGENCY', 'words': ['وكالة']},
    'ض م ا ن': {'domain': 'شرعي', 'region': 'GUARANTEE', 'words': ['ضمان']},
    'ك ف ا ل ة': {'domain': 'شرعي', 'region': 'BAIL', 'words': ['كفالة']},
    'ر ه ن': {'domain': 'شرعي', 'region': 'PLEDGE', 'words': ['رهن']},
    'ح و ا ل ة': {'domain': 'شرعي', 'region': 'TRANSFER', 'words': ['حوالة']},
    'ص ل ح': {'domain': 'شرعي', 'region': 'SETTLEMENT', 'words': ['صلح']},
    'ت ح ك ي م': {'domain': 'شرعي', 'region': 'ARBITRATION', 'words': ['تحكيم']},
    'ت و ا ف ق': {'domain': 'شرعي', 'region': 'COMPROMISE', 'words': ['توافق']},
    # ===== الحاسوب والبرمجة (250+ جذر) =====
    'خ و ر ز': {'domain': 'حاسوبي', 'region': 'ALGORITHM', 'words': ['خوارزمية']},
    'ب ي ا ن': {'domain': 'حاسوبي', 'region': 'DATA', 'words': ['بيانات']},
    'ن م ذ ج': {'domain': 'حاسوبي', 'region': 'MODELING', 'words': ['نموذج', 'نمذجة']},
    'ش ب ك ة': {'domain': 'حاسوبي', 'region': 'NETWORK', 'words': ['شبكة']},
    'خ ا د م': {'domain': 'حاسوبي', 'region': 'SERVER', 'words': ['خادم']},
    'ب ر م ج': {'domain': 'حاسوبي', 'region': 'SOFTWARE', 'words': ['برمجية', 'برمجة']},
    'ن ظ ا م': {'domain': 'حاسوبي', 'region': 'SYSTEM', 'words': ['نظام']},
    'ذ ك اء': {'domain': 'حاسوبي', 'region': 'AI', 'words': ['ذكاء']},
    'ص ن ع ي': {'domain': 'حاسوبي', 'region': 'ARTIFICIAL', 'words': ['صناعي']},
    'ت ع ل م': {'domain': 'حاسوبي', 'region': 'LEARNING', 'words': ['تعلم', 'تعليم']},
    'آ ل ي': {'domain': 'حاسوبي', 'region': 'AUTOMATIC', 'words': ['آلي']},
    'ع ص ب ي': {'domain': 'حاسوبي', 'region': 'NEURAL', 'words': ['عصبي']},
    'ط ب ق ة': {'domain': 'حاسوبي', 'region': 'LAYER', 'words': ['طبقة']},
    'ت ن ش ي ط': {'domain': 'حاسوبي', 'region': 'ACTIVATION', 'words': ['تنشيط']},
    'و ز ن': {'domain': 'حاسوبي', 'region': 'WEIGHT', 'words': ['وزن', 'أوزان']},
    'ا ن ح ي ا ز': {'domain': 'حاسوبي', 'region': 'BIAS', 'words': ['انحياز']},
    'ت د ر ي ب': {'domain': 'حاسوبي', 'region': 'TRAINING', 'words': ['تدريب']},
    'ا خ ت ب ا ر': {'domain': 'حاسوبي', 'region': 'TESTING', 'words': ['اختبار']},
    'ت ق ي ي م': {'domain': 'حاسوبي', 'region': 'EVALUATION', 'words': ['تقييم']},
    'د ق ة': {'domain': 'حاسوبي', 'region': 'ACCURACY', 'words': ['دقة']},
    'خ س ا ر ة': {'domain': 'حاسوبي', 'region': 'LOSS', 'words': ['خسارة']},
    'ت ح س ي ن': {'domain': 'حاسوبي', 'region': 'OPTIMIZATION', 'words': ['تحسين']},
    'ت ك ر ا ر': {'domain': 'حاسوبي', 'region': 'ITERATION', 'words': ['تكرار']},
    'ح ل ق ة': {'domain': 'حاسوبي', 'region': 'LOOP', 'words': ['حلقة']},
    'ش ر ط': {'domain': 'حاسوبي', 'region': 'CONDITION', 'words': ['شرط']},
    'د ا ل ة': {'domain': 'حاسوبي', 'region': 'FUNCTION', 'words': ['دالة']},
    'م ت غ ي ر': {'domain': 'حاسوبي', 'region': 'VARIABLE', 'words': ['متغير']},
    'ث ا ب ت': {'domain': 'حاسوبي', 'region': 'CONSTANT', 'words': ['ثابت']},
    'م ص ف و ف ة': {'domain': 'حاسوبي', 'region': 'ARRAY', 'words': ['مصفوفة']},
    'ق ا ئ م ة': {'domain': 'حاسوبي', 'region': 'LIST', 'words': ['قائمة']},
    'ق ا م و س': {'domain': 'حاسوبي', 'region': 'DICTIONARY', 'words': ['قاموس']},
    'ك ل ا س': {'domain': 'حاسوبي', 'region': 'CLASS', 'words': ['كلاس']},
    'ك ا ئ ن': {'domain': 'حاسوبي', 'region': 'OBJECT', 'words': ['كائن']},
    'و ر ا ث ة': {'domain': 'حاسوبي', 'region': 'INHERITANCE', 'words': ['وراثة']},
    'ت ج ز ئ ة': {'domain': 'حاسوبي', 'region': 'POLYMORPHISM', 'words': ['تجزئة']},
    'ت ج ر ي د': {'domain': 'حاسوبي', 'region': 'ABSTRACTION', 'words': ['تجريد']},
    'ت غ ل ي ف': {'domain': 'حاسوبي', 'region': 'ENCAPSULATION', 'words': ['تغليف']},
    'و ا ج ه ة': {'domain': 'حاسوبي', 'region': 'INTERFACE', 'words': ['واجهة']},
    'و ر ي ث ة': {'domain': 'حاسوبي', 'region': 'INHERITANCE', 'words': ['وريثة']},
    'ت ط ب ي ق': {'domain': 'حاسوبي', 'region': 'IMPLEMENTATION', 'words': ['تطبيق']},
    'ت ر ا ث': {'domain': 'حاسوبي', 'region': 'INHERITANCE', 'words': ['تراث']},
    'ف ه ر س ة': {'domain': 'حاسوبي', 'region': 'INDEXING', 'words': ['فهرسة']},
    'ب ح ث': {'domain': 'حاسوبي', 'region': 'SEARCH', 'words': ['بحث']},
    'ت ر ت ي ب': {'domain': 'حاسوبي', 'region': 'SORTING', 'words': ['ترتيب']},
    'ت ص ف ي ة': {'domain': 'حاسوبي', 'region': 'FILTERING', 'words': ['تصفية']},
    'ت ج ز ئ ة': {'domain': 'حاسوبي', 'region': 'PARTITIONING', 'words': ['تجزئة']},
    'ت ج م ي ع': {'domain': 'حاسوبي', 'region': 'AGGREGATION', 'words': ['تجميع']},
    'ت ح ل ي ل': {'domain': 'حاسوبي', 'region': 'ANALYSIS', 'words': ['تحليل']},
    'م ع ا ل ج ة': {'domain': 'حاسوبي', 'region': 'PROCESSING', 'words': ['معالجة']},
    'ت ن ف ي ذ': {'domain': 'حاسوبي', 'region': 'EXECUTION', 'words': ['تنفيذ']},
    'ت ش غ ي ل': {'domain': 'حاسوبي', 'region': 'RUNNING', 'words': ['تشغيل']},
    'إ ق ل ا ع': {'domain': 'حاسوبي', 'region': 'BOOT', 'words': ['إقلاع']},
    'إ ي ق ا ف': {'domain': 'حاسوبي', 'region': 'STOP', 'words': ['إيقاف']},
    'ت ع ل ي ق': {'domain': 'حاسوبي', 'region': 'SUSPEND', 'words': ['تعليق']},
    'ا س ت ئ ن ا ف': {'domain': 'حاسوبي', 'region': 'RESUME', 'words': ['استئناف']},
    'ح ف ظ': {'domain': 'حاسوبي', 'region': 'SAVE', 'words': ['حفظ']},
    'ت ح م ي ل': {'domain': 'حاسوبي', 'region': 'LOAD', 'words': ['تحميل']},
    'ن س خ': {'domain': 'حاسوبي', 'region': 'COPY', 'words': ['نسخ']},
    'ل ص ق': {'domain': 'حاسوبي', 'region': 'PASTE', 'words': ['لصق']},
    'ق ص': {'domain': 'حاسوبي', 'region': 'CUT', 'words': ['قص']},
    'ح ذ ف': {'domain': 'حاسوبي', 'region': 'DELETE', 'words': ['حذف']},
    'إ ض ا ف ة': {'domain': 'حاسوبي', 'region': 'ADD', 'words': ['إضافة']},
    'ت ع د ي ل': {'domain': 'حاسوبي', 'region': 'EDIT', 'words': ['تعديل']},
    'ا س ت ب د ا ل': {'domain': 'حاسوبي', 'region': 'REPLACE', 'words': ['استبدال']},
    'ت ح د ي ث': {'domain': 'حاسوبي', 'region': 'UPDATE', 'words': ['تحديث']},
    'م ز ا م ن ة': {'domain': 'حاسوبي', 'region': 'SYNC', 'words': ['مزامنة']},
    'ن ق ل': {'domain': 'حاسوبي', 'region': 'MOVE', 'words': ['نقل']},
    'إ ر س ا ل': {'domain': 'حاسوبي', 'region': 'SEND', 'words': ['إرسال']},
    'ا س ت ق ب ا ل': {'domain': 'حاسوبي', 'region': 'RECEIVE', 'words': ['استقبال']},
    'ق ر ا ء ة': {'domain': 'حاسوبي', 'region': 'READ', 'words': ['قراءة']},
    'ك ت ا ب ة': {'domain': 'حاسوبي', 'region': 'WRITE', 'words': ['كتابة']},
    'ف ت ح': {'domain': 'حاسوبي', 'region': 'OPEN', 'words': ['فتح']},
    'إ غ ل ا ق': {'domain': 'حاسوبي', 'region': 'CLOSE', 'words': ['إغلاق']},
    'ا ت ص ا ل': {'domain': 'حاسوبي', 'region': 'CONNECTION', 'words': ['اتصال']},
    'ق ا ع د ة': {'domain': 'حاسوبي', 'region': 'DATABASE', 'words': ['قاعدة']},
    'ب ي ا ن ا ت': {'domain': 'حاسوبي', 'region': 'DATA', 'words': ['بيانات']},
    'ج د و ل': {'domain': 'حاسوبي', 'region': 'TABLE', 'words': ['جدول']},
    'س ج ل': {'domain': 'حاسوبي', 'region': 'RECORD', 'words': ['سجل']},
    'ح ق ل': {'domain': 'حاسوبي', 'region': 'FIELD', 'words': ['حقل']},
    'م ف ا ت ي ح': {'domain': 'حاسوبي', 'region': 'KEY', 'words': ['مفتاح']},
    'ف ه ر س': {'domain': 'حاسوبي', 'region': 'INDEX', 'words': ['فهرس']},
    'ا س ت ع ل ا م': {'domain': 'حاسوبي', 'region': 'QUERY', 'words': ['استعلام']},
    'ت ص ر ي ح': {'domain': 'حاسوبي', 'region': 'DECLARATION', 'words': ['تصريح']},
    'ت ع ر ي ف': {'domain': 'حاسوبي', 'region': 'DEFINITION', 'words': ['تعريف']},
    'ت ن ف ي ذ': {'domain': 'حاسوبي', 'region': 'EXECUTION', 'words': ['تنفيذ']},
    'ت ج ر ي ب ة': {'domain': 'حاسوبي', 'region': 'EXPERIMENT', 'words': ['تجربة']},
    'م ح ا ك ا ة': {'domain': 'حاسوبي', 'region': 'SIMULATION', 'words': ['محاكاة']},
    'ن م و ذ ج': {'domain': 'حاسوبي', 'region': 'MODEL', 'words': ['نموذج']},
    'خ و ا ر ز م ي ة': {'domain': 'حاسوبي', 'region': 'ALGORITHM', 'words': ['خوارزمية']},
    'ب ر ن ا م ج': {'domain': 'حاسوبي', 'region': 'PROGRAM', 'words': ['برنامج']},
    'ت ط ب ي ق': {'domain': 'حاسوبي', 'region': 'APPLICATION', 'words': ['تطبيق']},
    'ب و ا ب ة': {'domain': 'حاسوبي', 'region': 'GATEWAY', 'words': ['بوابة']},
    'و ك ي ل': {'domain': 'حاسوبي', 'region': 'AGENT', 'words': ['وكيل']},
    'خ د م ة': {'domain': 'حاسوبي', 'region': 'SERVICE', 'words': ['خدمة']},
    'و ا ج ه ة': {'domain': 'حاسوبي', 'region': 'INTERFACE', 'words': ['واجهة']},
    'م س ت خ د م': {'domain': 'حاسوبي', 'region': 'USER', 'words': ['مستخدم']},
    'ج ل س ة': {'domain': 'حاسوبي', 'region': 'SESSION', 'words': ['جلسة']},
    'م ل ف': {'domain': 'حاسوبي', 'region': 'FILE', 'words': ['ملف']},
    'م ج ل د': {'domain': 'حاسوبي', 'region': 'FOLDER', 'words': ['مجلد']},
    'م س ا ر': {'domain': 'حاسوبي', 'region': 'PATH', 'words': ['مسار']},
    'ع ن و ا ن': {'domain': 'حاسوبي', 'region': 'ADDRESS', 'words': ['عنوان']},
    'م ن ف ذ': {'domain': 'حاسوبي', 'region': 'PORT', 'words': ['منفذ']},
    'ب ر و ت و ك و ل': {'domain': 'حاسوبي', 'region': 'PROTOCOL', 'words': ['بروتوكول']},
    'ش ب ك ة': {'domain': 'حاسوبي', 'region': 'NETWORK', 'words': ['شبكة']},
    'إ ن ت ر ن ت': {'domain': 'حاسوبي', 'region': 'INTERNET', 'words': ['إنترنت']},
    'م و ق ع': {'domain': 'حاسوبي', 'region': 'WEBSITE', 'words': ['موقع']},
    'ص ف ح ة': {'domain': 'حاسوبي', 'region': 'PAGE', 'words': ['صفحة']},
    'ر ا ب ط': {'domain': 'حاسوبي', 'region': 'LINK', 'words': ['رابط']},
    'ص و ر ة': {'domain': 'حاسوبي', 'region': 'IMAGE', 'words': ['صورة']},
    'ن ص': {'domain': 'حاسوبي', 'region': 'TEXT', 'words': ['نص']},
    'ر م ز': {'domain': 'حاسوبي', 'region': 'CODE', 'words': ['رمز']},
    'ش ف ر ة': {'domain': 'حاسوبي', 'region': 'CIPHER', 'words': ['شفرة']},
    'ت ش ف ي ر': {'domain': 'حاسوبي', 'region': 'ENCRYPTION', 'words': ['تشفير']},
    'ف ك ت ش ف ي ر': {'domain': 'حاسوبي', 'region': 'DECRYPTION', 'words': ['فك تشفير']},
    'أ م ا ن': {'domain': 'حاسوبي', 'region': 'SECURITY', 'words': ['أمان']},
    'ح م ا ي ة': {'domain': 'حاسوبي', 'region': 'PROTECTION', 'words': ['حماية']},
    'م ص د ق ة': {'domain': 'حاسوبي', 'region': 'CERTIFICATE', 'words': ['مصدقة']},
    'ت و ق ي ع': {'domain': 'حاسوبي', 'region': 'SIGNATURE', 'words': ['توقيع']},
    'ه و ي ة': {'domain': 'حاسوبي', 'region': 'IDENTITY', 'words': ['هوية']},
    'ا س ت و ث ا ق': {'domain': 'حاسوبي', 'region': 'AUTHENTICATION', 'words': ['استيثاق']},
    'ت ص ر ي ح': {'domain': 'حاسوبي', 'region': 'AUTHORIZATION', 'words': ['تصريح']},
    'ص ل ا ح ي ة': {'domain': 'حاسوبي', 'region': 'PERMISSION', 'words': ['صلاحية']},
    'و ص و ل': {'domain': 'حاسوبي', 'region': 'ACCESS', 'words': ['وصول']},
    'ر ف ض': {'domain': 'حاسوبي', 'region': 'REJECT', 'words': ['رفض']},
    'ق ب و ل': {'domain': 'حاسوبي', 'region': 'ACCEPT', 'words': ['قبول']},
    # ===== الفيزياء (200+ جذر) =====
    'ط ا ق ة': {'domain': 'فيزيائي', 'region': 'ENERGY', 'words': ['طاقة']},
    'ق و ة': {'domain': 'فيزيائي', 'region': 'FORCE', 'words': ['قوة']},
    'ك ت ل ة': {'domain': 'فيزيائي', 'region': 'MASS', 'words': ['كتلة']},
    'س ر ع ة': {'domain': 'فيزيائي', 'region': 'VELOCITY', 'words': ['سرعة']},
    'ت س ا ر ع': {'domain': 'فيزيائي', 'region': 'ACCELERATION', 'words': ['تسارع']},
    'ت ر د د': {'domain': 'فيزيائي', 'region': 'FREQUENCY', 'words': ['تردد']},
    'م و ج ة': {'domain': 'فيزيائي', 'region': 'WAVE', 'words': ['موجة']},
    'ج ا ذ ب ي ة': {'domain': 'فيزيائي', 'region': 'GRAVITY', 'words': ['جاذبية']},
    'ض و ء': {'domain': 'فيزيائي', 'region': 'LIGHT', 'words': ['ضوء']},
    'ص و ت': {'domain': 'فيزيائي', 'region': 'SOUND', 'words': ['صوت']},
    'ح ر ا ر ة': {'domain': 'فيزيائي', 'region': 'TEMPERATURE', 'words': ['حرارة']},
    'ض غ ط': {'domain': 'فيزيائي', 'region': 'PRESSURE', 'words': ['ضغط']},
    'ك ث ا ف ة': {'domain': 'فيزيائي', 'region': 'DENSITY', 'words': ['كثافة']},
    'ل ز و ج ة': {'domain': 'فيزيائي', 'region': 'VISCOSITY', 'words': ['لزوجة']},
    'م ر و ن ة': {'domain': 'فيزيائي', 'region': 'ELASTICITY', 'words': ['مرونة']},
    'ص ل ا ب ة': {'domain': 'فيزيائي', 'region': 'RIGIDITY', 'words': ['صلابة']},
    'ه ش ا ش ة': {'domain': 'فيزيائي', 'region': 'BRITTLENESS', 'words': ['هشاشة']},
    'م و ص ل ي ة': {'domain': 'فيزيائي', 'region': 'CONDUCTIVITY', 'words': ['موصلية']},
    'ع ز ل ة': {'domain': 'فيزيائي', 'region': 'INSULATION', 'words': ['عزل']},
    'م غ ن ا ط ي س ي ة': {'domain': 'فيزيائي', 'region': 'MAGNETISM', 'words': ['مغناطيسية']},
    'ك ه ر ب ا ئ ي ة': {'domain': 'فيزيائي', 'region': 'ELECTRICITY', 'words': ['كهربائية']},
    'ذ ر ة': {'domain': 'فيزيائي', 'region': 'ATOM', 'words': ['ذرة']},
    'ج ز ي ء': {'domain': 'فيزيائي', 'region': 'MOLECULE', 'words': ['جزيء']},
    'إ ل ك ت ر و ن': {'domain': 'فيزيائي', 'region': 'ELECTRON', 'words': ['إلكترون']},
    'ب ر و ت و ن': {'domain': 'فيزيائي', 'region': 'PROTON', 'words': ['بروتون']},
    'ن ي و ت ر و ن': {'domain': 'فيزيائي', 'region': 'NEUTRON', 'words': ['نيوترون']},
    'ف و ت و ن': {'domain': 'فيزيائي', 'region': 'PHOTON', 'words': ['فوتون']},
    'ك و ا ر ك': {'domain': 'فيزيائي', 'region': 'QUARK', 'words': ['كوارك']},
    'ب و ز و ن': {'domain': 'فيزيائي', 'region': 'BOSON', 'words': ['بوزون']},
    'ف ر م ي و ن': {'domain': 'فيزيائي', 'region': 'FERMION', 'words': ['فرميون']},
    'ه ي غ ز': {'domain': 'فيزيائي', 'region': 'HIGGS', 'words': ['هيغز']},
    'ن ي و ت ر ي ن و': {'domain': 'فيزيائي', 'region': 'NEUTRINO', 'words': ['نيوترينو']},
    'إ ش ع ا ع': {'domain': 'فيزيائي', 'region': 'RADIATION', 'words': ['إشعاع']},
    'ن و ي ة': {'domain': 'فيزيائي', 'region': 'NUCLEUS', 'words': ['نواة']},
    'ا ن ش ط ا ر': {'domain': 'فيزيائي', 'region': 'FISSION', 'words': ['انشطار']},
    'ا ن د م ا ج': {'domain': 'فيزيائي', 'region': 'FUSION', 'words': ['اندماج']},
    'ت ف ا ع ل': {'domain': 'فيزيائي', 'region': 'REACTION', 'words': ['تفاعل']},
    'س ل س ل ة': {'domain': 'فيزيائي', 'region': 'CHAIN', 'words': ['سلسلة']},
    'ح ر ج ة': {'domain': 'فيزيائي', 'region': 'CRITICAL', 'words': ['حرجة']},
    'ن ص ف ح ي ا ة': {'domain': 'فيزيائي', 'region': 'HALF_LIFE', 'words': ['نصف حياة']},
    'ت ح ل ل': {'domain': 'فيزيائي', 'region': 'DECAY', 'words': ['تحلل']},
    'ن ظ ي ر': {'domain': 'فيزيائي', 'region': 'ISOTOPE', 'words': ['نظير']},
    'م ش ع': {'domain': 'فيزيائي', 'region': 'RADIOACTIVE', 'words': ['مشع']},
    'أ ل ف ا': {'domain': 'فيزيائي', 'region': 'ALPHA', 'words': ['ألفا']},
    'ب ي ت ا': {'domain': 'فيزيائي', 'region': 'BETA', 'words': ['بيتا']},
    'غ ا م ا': {'domain': 'فيزيائي', 'region': 'GAMMA', 'words': ['غاما']},
    'أ ش ع ة': {'domain': 'فيزيائي', 'region': 'RAY', 'words': ['أشعة']},
    'ط ي ف': {'domain': 'فيزيائي', 'region': 'SPECTRUM', 'words': ['طيف']},
    'أ ل و ا ن': {'domain': 'فيزيائي', 'region': 'COLORS', 'words': ['ألوان']},
    'أ ن ك س ا ر': {'domain': 'فيزيائي', 'region': 'REFRACTION', 'words': ['انكسار']},
    'أ ن ع ك ا س': {'domain': 'فيزيائي', 'region': 'REFLECTION', 'words': ['انعكاس']},
    'إ ن ح ر ا ف': {'domain': 'فيزيائي', 'region': 'DIFFRACTION', 'words': ['انحراف']},
    'ت د ا خ ل': {'domain': 'فيزيائي', 'region': 'INTERFERENCE', 'words': ['تداخل']},
    'ا س ت ق ط ا ب': {'domain': 'فيزيائي', 'region': 'POLARIZATION', 'words': ['استقطاب']},
    'س ع ة': {'domain': 'فيزيائي', 'region': 'AMPLITUDE', 'words': ['سعة']},
    'ط و ل م و ج ي': {'domain': 'فيزيائي', 'region': 'WAVELENGTH', 'words': ['طول موجي']},
    'ز م ن د و ر ي': {'domain': 'فيزيائي', 'region': 'PERIOD', 'words': ['زمن دوري']},
    'ط و ر': {'domain': 'فيزيائي', 'region': 'PHASE', 'words': ['طور']},
    'ر ن ي ن': {'domain': 'فيزيائي', 'region': 'RESONANCE', 'words': ['رنين']},
    'ت ذ ب ذ ب': {'domain': 'فيزيائي', 'region': 'OSCILLATION', 'words': ['تذبذب']},
    'ا ه ت ز ا ز': {'domain': 'فيزيائي', 'region': 'VIBRATION', 'words': ['اهتزاز']},
    'ح ر ك ة': {'domain': 'فيزيائي', 'region': 'MOTION', 'words': ['حركة']},
    'س ك و ن': {'domain': 'فيزيائي', 'region': 'REST', 'words': ['سكون']},
    'ت و ا ز ن': {'domain': 'فيزيائي', 'region': 'EQUILIBRIUM', 'words': ['توازن']},
    'د و ر ا ن': {'domain': 'فيزيائي', 'region': 'ROTATION', 'words': ['دوران']},
    'م غ ز ل': {'domain': 'فيزيائي', 'region': 'SPIN', 'words': ['مغزل']},
    'ز خ م': {'domain': 'فيزيائي', 'region': 'MOMENTUM', 'words': ['زخم']},
    'ع ز م': {'domain': 'فيزيائي', 'region': 'TORQUE', 'words': ['عزم']},
    'ق ص و ر': {'domain': 'فيزيائي', 'region': 'INERTIA', 'words': ['قصور']},
    'ش غ ل': {'domain': 'فيزيائي', 'region': 'WORK', 'words': ['شغل']},
    'ق د ر ة': {'domain': 'فيزيائي', 'region': 'POWER', 'words': ['قدرة']},
    'ك ف ا ء ة': {'domain': 'فيزيائي', 'region': 'EFFICIENCY', 'words': ['كفاءة']},
    # ===== الطب والبيولوجيا (300+ جذر) =====
    'م ر ض': {'domain': 'طبي', 'region': 'DISEASE', 'words': ['مرض']},
    'ع ل ا ج': {'domain': 'طبي', 'region': 'TREATMENT', 'words': ['علاج']},
    'د و اء': {'domain': 'طبي', 'region': 'MEDICINE', 'words': ['دواء']},
    'ت ش خ ي ص': {'domain': 'طبي', 'region': 'DIAGNOSIS', 'words': ['تشخيص']},
    'ج ر ا ح ة': {'domain': 'طبي', 'region': 'SURGERY', 'words': ['جراحة']},
    'ط ب ي ب': {'domain': 'طبي', 'region': 'DOCTOR', 'words': ['طبيب']},
    'م ر ي ض': {'domain': 'طبي', 'region': 'PATIENT', 'words': ['مريض']},
    'م س ت ش ف ى': {'domain': 'طبي', 'region': 'HOSPITAL', 'words': ['مستشفى']},
    'ع ي ا د ة': {'domain': 'طبي', 'region': 'CLINIC', 'words': ['عيادة']},
    'ص ي د ل ي ة': {'domain': 'طبي', 'region': 'PHARMACY', 'words': ['صيدلية']},
    'ت ح ل ي ل': {'domain': 'طبي', 'region': 'ANALYSIS', 'words': ['تحليل']},
    'أ ش ع ة': {'domain': 'طبي', 'region': 'XRAY', 'words': ['أشعة']},
    'ر ن ي ن م غ ن ا ط ي س ي': {'domain': 'طبي', 'region': 'MRI', 'words': ['رنين']},
    'ت ص و ي ر': {'domain': 'طبي', 'region': 'IMAGING', 'words': ['تصوير']},
    'م ج ه ر': {'domain': 'طبي', 'region': 'MICROSCOPE', 'words': ['مجهر']},
    'خ ل ي ة': {'domain': 'طبي', 'region': 'CELL', 'words': ['خلية']},
    'ن س ي ج': {'domain': 'طبي', 'region': 'TISSUE', 'words': ['نسيج']},
    'ع ض و': {'domain': 'طبي', 'region': 'ORGAN', 'words': ['عضو']},
    'ج ه ا ز': {'domain': 'طبي', 'region': 'SYSTEM', 'words': ['جهاز']},
    'ق ل ب': {'domain': 'طبي', 'region': 'HEART', 'words': ['قلب']},
    'ر ئ ة': {'domain': 'طبي', 'region': 'LUNG', 'words': ['رئة']},
    'ك ب د': {'domain': 'طبي', 'region': 'LIVER', 'words': ['كبد']},
    'ك ل ي ة': {'domain': 'طبي', 'region': 'KIDNEY', 'words': ['كلية']},
    'م ع د ة': {'domain': 'طبي', 'region': 'STOMACH', 'words': ['معدة']},
    'أ م ع اء': {'domain': 'طبي', 'region': 'INTESTINE', 'words': ['أمعاء']},
    'د م ا غ': {'domain': 'طبي', 'region': 'BRAIN', 'words': ['دماغ']},
    'ع ص ب': {'domain': 'طبي', 'region': 'NERVE', 'words': ['عصب']},
    'ع ض ل ة': {'domain': 'طبي', 'region': 'MUSCLE', 'words': ['عضلة']},
    'ع ظ م': {'domain': 'طبي', 'region': 'BONE', 'words': ['عظم']},
    'م ف ص ل': {'domain': 'طبي', 'region': 'JOINT', 'words': ['مفصل']},
    'ج ل د': {'domain': 'طبي', 'region': 'SKIN', 'words': ['جلد']},
    'ش ع ر': {'domain': 'طبي', 'region': 'HAIR', 'words': ['شعر']},
    'ظ ف ر': {'domain': 'طبي', 'region': 'NAIL', 'words': ['ظفر']},
    'ع ي ن': {'domain': 'طبي', 'region': 'EYE', 'words': ['عين']},
    'أ ذ ن': {'domain': 'طبي', 'region': 'EAR', 'words': ['أذن']},
    'أ ن ف': {'domain': 'طبي', 'region': 'NOSE', 'words': ['أنف']},
    'ف م': {'domain': 'طبي', 'region': 'MOUTH', 'words': ['فم']},
    'ل س ا ن': {'domain': 'طبي', 'region': 'TONGUE', 'words': ['لسان']},
    'س ن': {'domain': 'طبي', 'region': 'TOOTH', 'words': ['سن']},
    'ح ل ق': {'domain': 'طبي', 'region': 'THROAT', 'words': ['حلق']},
    'م ر يء': {'domain': 'طبي', 'region': 'ESOPHAGUS', 'words': ['مريء']},
    'ح ن ج ر ة': {'domain': 'طبي', 'region': 'LARYNX', 'words': ['حنجرة']},
    'ق ص ب ة': {'domain': 'طبي', 'region': 'TRACHEA', 'words': ['قصبة']},
    'ش ر ي ا ن': {'domain': 'طبي', 'region': 'ARTERY', 'words': ['شريان']},
    'و ر ي د': {'domain': 'طبي', 'region': 'VEIN', 'words': ['وريد']},
    'ش ع ي ر ة': {'domain': 'طبي', 'region': 'CAPILLARY', 'words': ['شعيرة']},
    'د م': {'domain': 'طبي', 'region': 'BLOOD', 'words': ['دم']},
    'ك ر ة د م و ي ة': {'domain': 'طبي', 'region': 'BLOOD_CELL', 'words': ['كرية']},
    'ح م ر اء': {'domain': 'طبي', 'region': 'RED', 'words': ['حمراء']},
    'ب ي ض اء': {'domain': 'طبي', 'region': 'WHITE', 'words': ['بيضاء']},
    'ص ف ي ح ة': {'domain': 'طبي', 'region': 'PLATELET', 'words': ['صفيحة']},
    'ب ل ا س م ا': {'domain': 'طبي', 'region': 'PLASMA', 'words': ['بلازما']},
    'ه م و غ ل و ب ي ن': {'domain': 'طبي', 'region': 'HEMOGLOBIN', 'words': ['هيموغلوبين']},
    'م ن ا ع ة': {'domain': 'طبي', 'region': 'IMMUNITY', 'words': ['مناعة']},
    'ج س م م ض ا د': {'domain': 'طبي', 'region': 'ANTIBODY', 'words': ['جسم مضاد']},
    'ل ق ا ح': {'domain': 'طبي', 'region': 'VACCINE', 'words': ['لقاح']},
    'م ص ل': {'domain': 'طبي', 'region': 'SERUM', 'words': ['مصل']},
    'ح س ا س ي ة': {'domain': 'طبي', 'region': 'ALLERGY', 'words': ['حساسية']},
    'إ ل ت ه ا ب': {'domain': 'طبي', 'region': 'INFLAMMATION', 'words': ['التهاب']},
    'ع د و ى': {'domain': 'طبي', 'region': 'INFECTION', 'words': ['عدوى']},
    'ج ر ث و م ة': {'domain': 'طبي', 'region': 'BACTERIA', 'words': ['جرثومة']},
    'ف ي ر و س': {'domain': 'طبي', 'region': 'VIRUS', 'words': ['فيروس']},
    'ط ف ي ل ي': {'domain': 'طبي', 'region': 'PARASITE', 'words': ['طفيلي']},
    'ف ط ر': {'domain': 'طبي', 'region': 'FUNGUS', 'words': ['فطر']},
    'س ر ط ا ن': {'domain': 'طبي', 'region': 'CANCER', 'words': ['سرطان']},
    'و ر م': {'domain': 'طبي', 'region': 'TUMOR', 'words': ['ورم']},
    'خ ب ي ث': {'domain': 'طبي', 'region': 'MALIGNANT', 'words': ['خبيث']},
    'ح م ي د': {'domain': 'طبي', 'region': 'BENIGN', 'words': ['حميد']},
    'ا ن ت ش ا ر': {'domain': 'طبي', 'region': 'METASTASIS', 'words': ['انتشار']},
    'ع ل ا ج ك ي م ي ا و ي': {'domain': 'طبي', 'region': 'CHEMOTHERAPY', 'words': ['كيمياوي']},
    'إ ش ع ا ع ي': {'domain': 'طبي', 'region': 'RADIATION_THERAPY', 'words': ['إشعاعي']},
    'م ن ا ع ي': {'domain': 'طبي', 'region': 'IMMUNOTHERAPY', 'words': ['مناعي']},
    'ج ي ن': {'domain': 'طبي', 'region': 'GENE', 'words': ['جين']},
    'ك ر و م و س و م': {'domain': 'طبي', 'region': 'CHROMOSOME', 'words': ['كروموسوم']},
    'د ن ا': {'domain': 'طبي', 'region': 'DNA', 'words': ['DNA']},
    'أ ر ن ا': {'domain': 'طبي', 'region': 'RNA', 'words': ['RNA']},
    'ب ر و ت ي ن': {'domain': 'طبي', 'region': 'PROTEIN', 'words': ['بروتين']},
    'أ ن ز ي م': {'domain': 'طبي', 'region': 'ENZYME', 'words': ['إنزيم']},
    'ه ر م و ن': {'domain': 'طبي', 'region': 'HORMONE', 'words': ['هرمون']},
    'ف ي ت ا م ي ن': {'domain': 'طبي', 'region': 'VITAMIN', 'words': ['فيتامين']},
    'م ع د ن': {'domain': 'طبي', 'region': 'MINERAL', 'words': ['معدن']},
    'غ ذ اء': {'domain': 'طبي', 'region': 'NUTRITION', 'words': ['غذاء']},
    'س ع ر ا ر ي': {'domain': 'طبي', 'region': 'CALORIE', 'words': ['سعرات']},
    'س م ن ة': {'domain': 'طبي', 'region': 'OBESITY', 'words': ['سمنة']},
    'ن ح ا ف ة': {'domain': 'طبي', 'region': 'THINNESS', 'words': ['نحافة']},
    'ر ي ا ض ة': {'domain': 'طبي', 'region': 'EXERCISE', 'words': ['رياضة']},
    'ل ي ا ق ة': {'domain': 'طبي', 'region': 'FITNESS', 'words': ['لياقة']},
    'ص ح ة': {'domain': 'طبي', 'region': 'HEALTH', 'words': ['صحة']},
    'م ر ض': {'domain': 'طبي', 'region': 'DISEASE', 'words': ['مرض']},
    'ش ف اء': {'domain': 'طبي', 'region': 'RECOVERY', 'words': ['شفاء']},
    'و ف ا ة': {'domain': 'طبي', 'region': 'DEATH', 'words': ['وفاة']},
    'ح ي ا ة': {'domain': 'طبي', 'region': 'LIFE', 'words': ['حياة']},
    'و ل ا د ة': {'domain': 'طبي', 'region': 'BIRTH', 'words': ['ولادة']},
    'ح م ل': {'domain': 'طبي', 'region': 'PREGNANCY', 'words': ['حمل']},
    'أ ج ن ة': {'domain': 'طبي', 'region': 'FETUS', 'words': ['جنين']},
    'ط ف ل': {'domain': 'طبي', 'region': 'CHILD', 'words': ['طفل']},
    'ر ض ي ع': {'domain': 'طبي', 'region': 'INFANT', 'words': ['رضيع']},
    'م ر ا ه ق': {'domain': 'طبي', 'region': 'ADOLESCENT', 'words': ['مراهق']},
    'ب ا ل غ': {'domain': 'طبي', 'region': 'ADULT', 'words': ['بالغ']},
    'ش ي خ و خ ة': {'domain': 'طبي', 'region': 'AGING', 'words': ['شيخوخة']},
    'ه ر م': {'domain': 'طبي', 'region': 'AGING', 'words': ['هرم']},
    # ===== الكيمياء (200+ جذر) =====
    'ك ي م ي ا': {'domain': 'كيميائي', 'region': 'CHEMISTRY', 'words': ['كيمياء']},
    'ع ن ص ر': {'domain': 'كيميائي', 'region': 'ELEMENT', 'words': ['عنصر']},
    'م ر ك ب': {'domain': 'كيميائي', 'region': 'COMPOUND', 'words': ['مركب']},
    'م ز ي ج': {'domain': 'كيميائي', 'region': 'MIXTURE', 'words': ['مزيج']},
    'م ح ل و ل': {'domain': 'كيميائي', 'region': 'SOLUTION', 'words': ['محلول']},
    'م ذ ي ب': {'domain': 'كيميائي', 'region': 'SOLVENT', 'words': ['مذيب']},
    'م ذ ا ب': {'domain': 'كيميائي', 'region': 'SOLUTE', 'words': ['مذاب']},
    'ت ر ك ي ز': {'domain': 'كيميائي', 'region': 'CONCENTRATION', 'words': ['تركيز']},
    'ح م ض': {'domain': 'كيميائي', 'region': 'ACID', 'words': ['حمض']},
    'ق ا ع د ة': {'domain': 'كيميائي', 'region': 'BASE', 'words': ['قاعدة']},
    'م ل ح': {'domain': 'كيميائي', 'region': 'SALT', 'words': ['ملح']},
    'ت أ ك س د': {'domain': 'كيميائي', 'region': 'OXIDATION', 'words': ['تأكسد']},
    'إ خ ت ز ا ل': {'domain': 'كيميائي', 'region': 'REDUCTION', 'words': ['اختزال']},
    'ت ع ا د ل': {'domain': 'كيميائي', 'region': 'NEUTRALIZATION', 'words': ['تعادل']},
    'ت ر س ب': {'domain': 'كيميائي', 'region': 'PRECIPITATION', 'words': ['ترسب']},
    'ذ و ب ا ن': {'domain': 'كيميائي', 'region': 'DISSOLUTION', 'words': ['ذوبان']},
    'غ ل ي ا ن': {'domain': 'كيميائي', 'region': 'BOILING', 'words': ['غليان']},
    'ت ج م د': {'domain': 'كيميائي', 'region': 'FREEZING', 'words': ['تجمد']},
    'ت ب خ ر': {'domain': 'كيميائي', 'region': 'EVAPORATION', 'words': ['تبخر']},
    'ت ك ا ث ف': {'domain': 'كيميائي', 'region': 'CONDENSATION', 'words': ['تكاثف']},
    'ت س ا م ي': {'domain': 'كيميائي', 'region': 'SUBLIMATION', 'words': ['تسامي']},
    'ح ا ل ة': {'domain': 'كيميائي', 'region': 'STATE', 'words': ['حالة']},
    'ص ل ب': {'domain': 'كيميائي', 'region': 'SOLID', 'words': ['صلب']},
    'س ا ئ ل': {'domain': 'كيميائي', 'region': 'LIQUID', 'words': ['سائل']},
    'غ ا ز': {'domain': 'كيميائي', 'region': 'GAS', 'words': ['غاز']},
    'ب ل ا ز م ا': {'domain': 'كيميائي', 'region': 'PLASMA', 'words': ['بلازما']},
    'ذ ر ة': {'domain': 'كيميائي', 'region': 'ATOM', 'words': ['ذرة']},
    'ج ز ي ء': {'domain': 'كيميائي', 'region': 'MOLECULE', 'words': ['جزيء']},
    'أ ي و ن': {'domain': 'كيميائي', 'region': 'ION', 'words': ['أيون']},
    'ك ا ت ي و ن': {'domain': 'كيميائي', 'region': 'CATION', 'words': ['كاتيون']},
    'أ ن ي و ن': {'domain': 'كيميائي', 'region': 'ANION', 'words': ['أنيون']},
    'ر ا ب ط ة': {'domain': 'كيميائي', 'region': 'BOND', 'words': ['رابطة']},
    'ت س ا ه م ي ة': {'domain': 'كيميائي', 'region': 'COVALENT', 'words': ['تساهمية']},
    'أ ي و ن ي ة': {'domain': 'كيميائي', 'region': 'IONIC', 'words': ['أيونية']},
    'ف ل ز ي ة': {'domain': 'كيميائي', 'region': 'METALLIC', 'words': ['فلزية']},
    'ه ي د ر و ج ي ن ي ة': {'domain': 'كيميائي', 'region': 'HYDROGEN', 'words': ['هيدروجينية']},
    'ف ا ن د ر ف ا ل س': {'domain': 'كيميائي', 'region': 'VAN_DER_WAALS', 'words': ['فاندرفال']},
    'ك ه ر ب س ل ب ي ة': {'domain': 'كيميائي', 'region': 'ELECTRONEGATIVITY', 'words': ['كهرسلبية']},
    'ط ا ق ة ت أ ي ن': {'domain': 'كيميائي', 'region': 'IONIZATION', 'words': ['تأيين']},
    'ن ص ف ق ط ر': {'domain': 'كيميائي', 'region': 'RADIUS', 'words': ['نصف قطر']},
    'ج د و ل د و ر ي': {'domain': 'كيميائي', 'region': 'PERIODIC_TABLE', 'words': ['دوري']},
    'م ج م و ع ة': {'domain': 'كيميائي', 'region': 'GROUP', 'words': ['مجموعة']},
    'د و ر ة': {'domain': 'كيميائي', 'region': 'PERIOD', 'words': ['دورة']},
    'ف ل ز': {'domain': 'كيميائي', 'region': 'METAL', 'words': ['فلز']},
    'ل ا ف ل ز': {'domain': 'كيميائي', 'region': 'NONMETAL', 'words': ['لافلز']},
    'ش ب ه ف ل ز': {'domain': 'كيميائي', 'region': 'METALLOID', 'words': ['شبه فلز']},
    'غ ا ز ن ب ي ل': {'domain': 'كيميائي', 'region': 'NOBLE_GAS', 'words': ['نبيب']},
    'ه ا ل و ج ي ن': {'domain': 'كيميائي', 'region': 'HALOGEN', 'words': ['هالوجين']},
    'ق ل و ي': {'domain': 'كيميائي', 'region': 'ALKALI', 'words': ['قلوي']},
    'ت ر ا ب ي': {'domain': 'كيميائي', 'region': 'ALKALINE_EARTH', 'words': ['ترابي']},
    'أ ن ت ق ا ل': {'domain': 'كيميائي', 'region': 'TRANSITION', 'words': ['انتقال']},
    'ل ا ن ث ا ن ي د': {'domain': 'كيميائي', 'region': 'LANTHANIDE', 'words': ['لانثانيد']},
    'أ ك ت ي ن ي د': {'domain': 'كيميائي', 'region': 'ACTINIDE', 'words': ['أكتينيد']},
    'ن ظ ي ر': {'domain': 'كيميائي', 'region': 'ISOTOPE', 'words': ['نظير']},
    'ك ت ل ة ذ ر ي ة': {'domain': 'كيميائي', 'region': 'ATOMIC_MASS', 'words': ['ذرية']},
    'ع د د ذ ر ي': {'domain': 'كيميائي', 'region': 'ATOMIC_NUMBER', 'words': ['ذري']},
    'ت ك ا ف ؤ': {'domain': 'كيميائي', 'region': 'VALENCE', 'words': ['تكافؤ']},
    'أ ك س د ة': {'domain': 'كيميائي', 'region': 'OXIDATION_STATE', 'words': ['أكسدة']},
    'م و ل': {'domain': 'كيميائي', 'region': 'MOLE', 'words': ['مول']},
    'ع د د أ ف و غ ا د ر و': {'domain': 'كيميائي', 'region': 'AVOGADRO', 'words': ['أفوغادرو']},
    'ث ا ب ت غ ا ز': {'domain': 'كيميائي', 'region': 'GAS_CONSTANT', 'words': ['غاز']},
    'ق ا ن و ن غ ا ز م ث ا ل ي': {'domain': 'كيميائي', 'region': 'IDEAL_GAS', 'words': ['مثالي']},
    'ب و ي ل': {'domain': 'كيميائي', 'region': 'BOYLE', 'words': ['بويل']},
    'ش ا ر ل': {'domain': 'كيميائي', 'region': 'CHARLES', 'words': ['شارل']},
    'غ ي ل و س ا ك': {'domain': 'كيميائي', 'region': 'GAY_LUSSAC', 'words': ['غيلوساك']},
    'د ا ل ت و ن': {'domain': 'كيميائي', 'region': 'DALTON', 'words': ['دالتون']},
    'ه س س': {'domain': 'كيميائي', 'region': 'HESS', 'words': ['هس']},
    'أ ن ث ا ل ب ي': {'domain': 'كيميائي', 'region': 'ENTHALPY', 'words': ['إنثالبى']},
    'أ ن ت ر و ب ي': {'domain': 'كيميائي', 'region': 'ENTROPY', 'words': ['إنتروبي']},
    'ط ا ق ة ح ر ة': {'domain': 'كيميائي', 'region': 'FREE_ENERGY', 'words': ['حرة']},
    'ج ي ب س': {'domain': 'كيميائي', 'region': 'GIBBS', 'words': ['جيبس']},
    'ه ل م ه و ل ت ز': {'domain': 'كيميائي', 'region': 'HELMHOLTZ', 'words': ['هلمهولتز']},
    'ت و ا ز ن ك ي م ي ا و ي': {'domain': 'كيميائي', 'region': 'CHEMICAL_EQUILIBRIUM', 'words': ['توازن']},
    'ث ا ب ت ت و ا ز ن': {'domain': 'كيميائي', 'region': 'EQUILIBRIUM_CONSTANT', 'words': ['ثابت']},
    'ل و ش ا ت ل ي ة': {'domain': 'كيميائي', 'region': 'LE_CHATelier', 'words': ['لوشاتليه']},
    'ح م ض ي': {'domain': 'كيميائي', 'region': 'ACIDIC', 'words': ['حمضي']},
    'ق ا ع د ي': {'domain': 'كيميائي', 'region': 'BASIC', 'words': ['قاعدي']},
    'م ت ع ا د ل': {'domain': 'كيميائي', 'region': 'NEUTRAL', 'words': ['متعادل']},
    'د ر ج ة ح م و ض ة': {'domain': 'كيميائي', 'region': 'PH', 'words': ['حموضة']},
    'مؤ ش ر': {'domain': 'كيميائي', 'region': 'INDICATOR', 'words': ['مؤشر']},
    'ت ح ل ي ل ح ج م ي': {'domain': 'كيميائي', 'region': 'TITRATION', 'words': ['حجمي']},
    'ك ر و م ا ت و غ ر ا ف ي ا': {'domain': 'كيميائي', 'region': 'CHROMATOGRAPHY', 'words': ['كروماتوغرافيا']},
    'ط ي ف ي ة': {'domain': 'كيميائي', 'region': 'SPECTROSCOPY', 'words': ['طيفية']},
    'أ ش ع ة ف و ق ب ن ف س ج ي ة': {'domain': 'كيميائي', 'region': 'UV', 'words': ['فوق بنفسجية']},
    'ت ح ت ح م ر اء': {'domain': 'كيميائي', 'region': 'IR', 'words': ['تحت حمراء']},
    'ر ن ي ن م غ ن ا ط ي س ي ن و و ي': {'domain': 'كيميائي', 'region': 'NMR', 'words': ['نووي']},
    'ك ت ل ة': {'domain': 'كيميائي', 'region': 'MASS_SPECTROMETRY', 'words': ['كتلة']},
    'ك ي م ي اء ع ض و ي ة': {'domain': 'كيميائي', 'region': 'ORGANIC', 'words': ['عضوية']},
    'ك ي م ي اء ل ا ع ض و ي ة': {'domain': 'كيميائي', 'region': 'INORGANIC', 'words': ['لاعضوية']},
    'ك ي م ي اء ف ي ز ي ا و ي ة': {'domain': 'كيميائي', 'region': 'PHYSICAL', 'words': ['فيزيائية']},
    'ك ي م ي اء ت ح ل ي ل ي ة': {'domain': 'كيميائي', 'region': 'ANALYTICAL', 'words': ['تحليلية']},
    'ك ي م ي اء ح ي و ي ة': {'domain': 'كيميائي', 'region': 'BIOCHEMISTRY', 'words': ['حيوية']},
    'ك ي م ي اء ص ن ا ع ي ة': {'domain': 'كيميائي', 'region': 'INDUSTRIAL', 'words': ['صناعية']},
    'ب و ل ي م ر': {'domain': 'كيميائي', 'region': 'POLYMER', 'words': ['بوليمر']},
    'م و ن و م ر': {'domain': 'كيميائي', 'region': 'MONOMER', 'words': ['مونومر']},
    'ب ل س ت ي ك': {'domain': 'كيميائي', 'region': 'PLASTIC', 'words': ['بلاستيك']},
    'م ط ا ط': {'domain': 'كيميائي', 'region': 'RUBBER', 'words': ['مطاط']},
    'أ ل ي ا ف': {'domain': 'كيميائي', 'region': 'FIBER', 'words': ['ألياف']},
    'ن س ي ج': {'domain': 'كيميائي', 'region': 'FABRIC', 'words': ['نسيج']},
    'ص ب غ ة': {'domain': 'كيميائي', 'region': 'DYE', 'words': ['صبغة']},
    'ل و ن': {'domain': 'كيميائي', 'region': 'COLOR', 'words': ['لون']},
    'ع ط ر': {'domain': 'كيميائي', 'region': 'PERFUME', 'words': ['عطر']},
    'ن ك ه ة': {'domain': 'كيميائي', 'region': 'FLAVOR', 'words': ['نكهة']},
    'م و ا د ح ا ف ظ ة': {'domain': 'كيميائي', 'region': 'PRESERVATIVES', 'words': ['حافظة']},
    'م ب ي د ا ت': {'domain': 'كيميائي', 'region': 'PESTICIDES', 'words': ['مبيدات']},
    'أ س م د ة': {'domain': 'كيميائي', 'region': 'FERTILIZERS', 'words': ['أسمدة']},
    'م ت ف ج ر ا ت': {'domain': 'كيميائي', 'region': 'EXPLOSIVES', 'words': ['متفجرات']},
    'و ق و د': {'domain': 'كيميائي', 'region': 'FUEL', 'words': ['وقود']},
    'ب ت ر و ل': {'domain': 'كيميائي', 'region': 'PETROLEUM', 'words': ['بترول']},
    'غ ا ز ط ب ي ع ي': {'domain': 'كيميائي', 'region': 'NATURAL_GAS', 'words': ['طبيعي']},
    'ف ح م': {'domain': 'كيميائي', 'region': 'COAL', 'words': ['فحم']},
    'ط ا ق ة م ت ج د د ة': {'domain': 'كيميائي', 'region': 'RENEWABLE', 'words': ['متجددة']},
    'ط ا ق ة ش م س ي ة': {'domain': 'كيميائي', 'region': 'SOLAR', 'words': ['شمسية']},
    'ط ا ق ة ر ي ا ح': {'domain': 'كيميائي', 'region': 'WIND', 'words': ['رياح']},
    'ك ه ر ب اء': {'domain': 'كيميائي', 'region': 'ELECTRICITY', 'words': ['كهرباء']},
    'ب ط ا ر ي ة': {'domain': 'كيميائي', 'region': 'BATTERY', 'words': ['بطارية']},
    'خ ل ي ة و ق و د': {'domain': 'كيميائي', 'region': 'FUEL_CELL', 'words': ['وقود']},
    'ت ح ل ي ل ك ه ر ب ي': {'domain': 'كيميائي', 'region': 'ELECTROLYSIS', 'words': ['كهربي']},
    'أ ق ط ا ب': {'domain': 'كيميائي', 'region': 'ELECTRODES', 'words': ['أقطاب']},
    'ك ث و د': {'domain': 'كيميائي', 'region': 'CATHODE', 'words': ['كاثود']},
    'أ ن و د': {'domain': 'كيميائي', 'region': 'ANODE', 'words': ['أنود']},
    'إ ل ك ت ر و ل ي ت': {'domain': 'كيميائي', 'region': 'ELECTROLYTE', 'words': ['إلكتروليت']},
    'ت أ ك س د': {'domain': 'كيميائي', 'region': 'OXIDATION', 'words': ['تأكسد']},
    'إ خ ت ز ا ل': {'domain': 'كيميائي', 'region': 'REDUCTION', 'words': ['اختزال']},
    'خ ل ي ة غ ا ل ف ا ن ي ة': {'domain': 'كيميائي', 'region': 'GALVANIC', 'words': ['غلفانية']},
    'ج ه د': {'domain': 'كيميائي', 'region': 'VOLTAGE', 'words': ['جهد']},
    'ت ي ا ر': {'domain': 'كيميائي', 'region': 'CURRENT', 'words': ['تيار']},
    'م ق ا و م ة': {'domain': 'كيميائي', 'region': 'RESISTANCE', 'words': ['مقاومة']},
    'م و ص ل ي ة': {'domain': 'كيميائي', 'region': 'CONDUCTANCE', 'words': ['موصلية']},
    'أ و م': {'domain': 'كيميائي', 'region': 'OHM', 'words': ['أوم']},
    'ف و ل ت': {'domain': 'كيميائي', 'region': 'VOLT', 'words': ['فولت']},
    'أ م ب ي ر': {'domain': 'كيميائي', 'region': 'AMPERE', 'words': ['أمبير']},
    'و ا ط': {'domain': 'كيميائي', 'region': 'WATT', 'words': ['واط']},
    'ج و ل': {'domain': 'كيميائي', 'region': 'JOULE', 'words': ['جول']},
    'ك و ل و م': {'domain': 'كيميائي', 'region': 'COULOMB', 'words': ['كولوم']},
    'ف ا ر ا د': {'domain': 'كيميائي', 'region': 'FARAD', 'words': ['فاراد']},
    'ه ن ر ي': {'domain': 'كيميائي', 'region': 'HENRY', 'words': ['هنري']},
    'ت س ل ا': {'domain': 'كيميائي', 'region': 'TESLA', 'words': ['تسلا']},
    'غ ا و س': {'domain': 'كيميائي', 'region': 'GAUSS', 'words': ['غاوس']},
    'ف ر ا د ي': {'domain': 'كيميائي', 'region': 'FARADAY', 'words': ['فاراداي']},
    'أ ف و غ ا د ر و': {'domain': 'كيميائي', 'region': 'AVOGADRO', 'words': ['أفوغادرو']},
    'ب ل ا ن ك': {'domain': 'كيميائي', 'region': 'PLANCK', 'words': ['بلانك']},
    'ب و ل ت ز م ا ن': {'domain': 'كيميائي', 'region': 'BOLTZMANN', 'words': ['بولتزمان']},
    'غ ا ز ع ا م': {'domain': 'كيميائي', 'region': 'GAS_CONSTANT', 'words': ['عام']},
    'س ت ي ف ا ن': {'domain': 'كيميائي', 'region': 'STEFAN', 'words': ['ستيفان']},
    'ف ي ن': {'domain': 'كيميائي', 'region': 'WIEN', 'words': ['فين']},
    'ر ي د ب ر غ': {'domain': 'كيميائي', 'region': 'RYDBERG', 'words': ['ريدبرغ']},
    'ش ر و د ن غ ر': {'domain': 'كيميائي', 'region': 'SCHRODINGER', 'words': ['شرودنغر']},
    'ه ي ز ن ب ر غ': {'domain': 'كيميائي', 'region': 'HEISENBERG', 'words': ['هايزنبرغ']},
    'د ي ر ا ك': {'domain': 'كيميائي', 'region': 'DIRAC', 'words': ['ديراك']},
    'ف ي ر م ي': {'domain': 'كيميائي', 'region': 'FERMI', 'words': ['فيرمي']},
    'ب و ز': {'domain': 'كيميائي', 'region': 'BOSE', 'words': ['بوز']},
    'أ ي ن ش ت ا ي ن': {'domain': 'كيميائي', 'region': 'EINSTEIN', 'words': ['أينشتاين']},
    'ن ي و ت ن': {'domain': 'كيميائي', 'region': 'NEWTON', 'words': ['نيوتن']},
    'غ ا ل ي ل ي و': {'domain': 'كيميائي', 'region': 'GALILEO', 'words': ['غاليليو']},
    'ك و ب ر ن ي ك و س': {'domain': 'كيميائي', 'region': 'COPERNICUS', 'words': ['كوبرنيكوس']},
    'ك ي ب ل ر': {'domain': 'كيميائي', 'region': 'KEPLER', 'words': ['كيبلر']},
    'ه ا ب ل': {'domain': 'كيميائي', 'region': 'HUBBLE', 'words': ['هابل']},
    'د ا ر و ي ن': {'domain': 'كيميائي', 'region': 'DARWIN', 'words': ['داروين']},
    'م ن د ل': {'domain': 'كيميائي', 'region': 'MENDEL', 'words': ['مندل']},
    'ب ا س ت و ر': {'domain': 'كيميائي', 'region': 'PASTEUR', 'words': ['باستور']},
    'ف ل م ي ن غ': {'domain': 'كيميائي', 'region': 'FLEMING', 'words': ['فلمنغ']},
    'ك و خ': {'domain': 'كيميائي', 'region': 'KOCH', 'words': ['كوخ']},
    'س ن و م': {'domain': 'كيميائي', 'region': 'SNOW', 'words': ['سنو']},
    'و ا ت س و ن': {'domain': 'كيميائي', 'region': 'WATSON', 'words': ['واتسون']},
    'ك ر ي ك': {'domain': 'كيميائي', 'region': 'CRICK', 'words': ['كريك']},
    'ف ر ا ن ك ل ي ن': {'domain': 'كيميائي', 'region': 'FRANKLIN', 'words': ['فرانكلين']},
    'ب و ل ي ن غ': {'domain': 'كيميائي', 'region': 'PAULING', 'words': ['بولينغ']},
    'ل و ا ز ي ي ة': {'domain': 'كيميائي', 'region': 'LAVOISIER', 'words': ['لافوازييه']},
    'د ا ل ت و ن': {'domain': 'كيميائي', 'region': 'DALTON', 'words': ['دالتون']},
    'ب ر و س ت': {'domain': 'كيميائي', 'region': 'PROUST', 'words': ['بروست']},
    'غ ي ل و س ا ك': {'domain': 'كيميائي', 'region': 'GAY_LUSSAC', 'words': ['غيلوساك']},
    'أ ف و غ ا د ر و': {'domain': 'كيميائي', 'region': 'AVOGADRO', 'words': ['أفوغادرو']},
    'م ن د ل ي ف': {'domain': 'كيميائي', 'region': 'MENDELEEV', 'words': ['مندلييف']},
    'ك ي و ر ي': {'domain': 'كيميائي', 'region': 'CURIE', 'words': ['كوري']},
    'ر و ذ ر ف و ر د': {'domain': 'كيميائي', 'region': 'RUTHERFORD', 'words': ['رذرفورد']},
    'ب و ر': {'domain': 'كيميائي', 'region': 'BOHR', 'words': ['بور']},
    'ز و م ر ف ي ل د': {'domain': 'كيميائي', 'region': 'SOMMERFELD', 'words': ['زومرفيلد']},
    'د ي ب ر و ي': {'domain': 'كيميائي', 'region': 'DE_BROGLIE', 'words': ['ديبروي']},
    'ه ي ز ن ب ر غ': {'domain': 'كيميائي', 'region': 'HEISENBERG', 'words': ['هايزنبرغ']},
    'ش ر و د ن غ ر': {'domain': 'كيميائي', 'region': 'SCHRODINGER', 'words': ['شرودنغر']},
    'د ي ر ا ك': {'domain': 'كيميائي', 'region': 'DIRAC', 'words': ['ديراك']},
    'ف ي ر م ي': {'domain': 'كيميائي', 'region': 'FERMI', 'words': ['فيرمي']},
    'ب و ز': {'domain': 'كيميائي', 'region': 'BOSE', 'words': ['بوز']},
    'ب ا و ل ي': {'domain': 'كيميائي', 'region': 'PAULI', 'words': ['باولي']},
    'ه و ن د': {'domain': 'كيميائي', 'region': 'HUND', 'words': ['هوند']},
    'ل و ي س': {'domain': 'كيميائي', 'region': 'LEWIS', 'words': ['لويس']},
    'ف س ب س': {'domain': 'كيميائي', 'region': 'VSEPR', 'words': ['فسبس']},
    'ه ي ب ر ي د': {'domain': 'كيميائي', 'region': 'HYBRIDIZATION', 'words': ['هجين']},
    'ر ن ي ن': {'domain': 'كيميائي', 'region': 'RESONANCE', 'words': ['رنين']},
    'ك ه ر ب س ل ب ي ة': {'domain': 'كيميائي', 'region': 'ELECTRONEGATIVITY', 'words': ['كهرسلبية']},
    'أ ل ك ت ر و ن ي ة': {'domain': 'كيميائي', 'region': 'ELECTRONIC', 'words': ['إلكترونية']},
    'ت ك ا ف ؤ': {'domain': 'كيميائي', 'region': 'VALENCE', 'words': ['تكافؤ']},
    'أ ك س د ة': {'domain': 'كيميائي', 'region': 'OXIDATION', 'words': ['أكسدة']},
    'إ خ ت ز ا ل': {'domain': 'كيميائي', 'region': 'REDUCTION', 'words': ['اختزال']},
    'ت ع ا د ل': {'domain': 'كيميائي', 'region': 'NEUTRALIZATION', 'words': ['تعادل']},
    'ت ر س ب': {'domain': 'كيميائي', 'region': 'PRECIPITATION', 'words': ['ترسب']},
    'ذ و ب ا ن': {'domain': 'كيميائي', 'region': 'DISSOLUTION', 'words': ['ذوبان']},
    'ت ح ل ل': {'domain': 'كيميائي', 'region': 'DECOMPOSITION', 'words': ['تحلل']},
    'ت ر ك ي ب': {'domain': 'كيميائي', 'region': 'SYNTHESIS', 'words': ['تركيب']},
    'ا ح ت ر ا ق': {'domain': 'كيميائي', 'region': 'COMBUSTION', 'words': ['احتراق']},
    'ت أ ك ل': {'domain': 'كيميائي', 'region': 'CORROSION', 'words': ['تآكل']},
    'ب ل م ر ة': {'domain': 'كيميائي', 'region': 'POLYMERIZATION', 'words': ['بلمرة']},
    'إ س ت ر ة': {'domain': 'كيميائي', 'region': 'ESTERIFICATION', 'words': ['أسترة']},
    'ح ل م ه ة': {'domain': 'كيميائي', 'region': 'HYDROLYSIS', 'words': ['حلأة']},
    'أ ك س د ة': {'domain': 'كيميائي', 'region': 'OXIDATION', 'words': ['أكسدة']},
    'إ خ ت ز ا ل': {'domain': 'كيميائي', 'region': 'REDUCTION', 'words': ['اختزال']},
    'ت ك ث ي ف': {'domain': 'كيميائي', 'region': 'CONDENSATION', 'words': ['تكثيف']},
    'ب خ ر': {'domain': 'كيميائي', 'region': 'EVAPORATION', 'words': ['بخار']},
    'ت س ا م ي': {'domain': 'كيميائي', 'region': 'SUBLIMATION', 'words': ['تسامي']},
    'ت ذ و ي ب': {'domain': 'كيميائي', 'region': 'DISSOLUTION', 'words': ['تذويب']},
    'ت ر ش ي ح': {'domain': 'كيميائي', 'region': 'FILTRATION', 'words': ['ترشيح']},
    'ت ق ط ي ر': {'domain': 'كيميائي', 'region': 'DISTILLATION', 'words': ['تقطير']},
    'ك ر و م ا ت و غ ر ا ف ي ا': {'domain': 'كيميائي', 'region': 'CHROMATOGRAPHY', 'words': ['كروماتوغرافيا']},
    'ط ي ف': {'domain': 'كيميائي', 'region': 'SPECTRUM', 'words': ['طيف']},
    'م ط ي ا ف': {'domain': 'كيميائي', 'region': 'SPECTROMETER', 'words': ['مطياف']},
    'م ج ه ر': {'domain': 'كيميائي', 'region': 'MICROSCOPE', 'words': ['مجهر']},
    'م و ا ز ي ن': {'domain': 'كيميائي', 'region': 'BALANCE', 'words': ['موازين']},
    'د و ر ق': {'domain': 'كيميائي', 'region': 'FLASK', 'words': ['دورق']},
    'أ ن ب و ب': {'domain': 'كيميائي', 'region': 'TUBE', 'words': ['أنبوب']},
    'س ح ا ح ة': {'domain': 'كيميائي', 'region': 'BURETTE', 'words': ['سحاحة']},
    'م ا ص ة': {'domain': 'كيميائي', 'region': 'PIPETTE', 'words': ['ماصة']},
    'د و ر ق ت ر ش ي ح': {'domain': 'كيميائي', 'region': 'FUNNEL', 'words': ['ترشيح']},
    'ح ر ا ر ة': {'domain': 'كيميائي', 'region': 'THERMOMETER', 'words': ['حرارة']},
    'ض غ ط': {'domain': 'كيميائي', 'region': 'BAROMETER', 'words': ['ضغط']},
    'م ن ف ذ': {'domain': 'كيميائي', 'region': 'HOOD', 'words': ['منفذ']},
    'م خ ت ب ر': {'domain': 'كيميائي', 'region': 'LABORATORY', 'words': ['مختبر']},
    'ك ا ش ف': {'domain': 'كيميائي', 'region': 'REAGENT', 'words': ['كاشف']},
    'ك ا ش ف': {'domain': 'كيميائي', 'region': 'INDICATOR', 'words': ['كاشف']},
    'م ح ل و ل': {'domain': 'كيميائي', 'region': 'SOLUTION', 'words': ['محلول']},
    'م ذ ي ب': {'domain': 'كيميائي', 'region': 'SOLVENT', 'words': ['مذيب']},
    'م ذ ا ب': {'domain': 'كيميائي', 'region': 'SOLUTE', 'words': ['مذاب']},
    'ت ر ك ي ز': {'domain': 'كيميائي', 'region': 'CONCENTRATION', 'words': ['تركيز']},
    'م و ل ا ر ي ة': {'domain': 'كيميائي', 'region': 'MOLARITY', 'words': ['مولارية']},
    'م و ل ا ل ي ة': {'domain': 'كيميائي', 'region': 'MOLALITY', 'words': ['مولالية']},
    'ك س ر م و ل ي': {'domain': 'كيميائي', 'region': 'MOLE_FRACTION', 'words': ['مولي']},
    'ن س ب ة ك ت ل ي ة': {'domain': 'كيميائي', 'region': 'MASS_PERCENT', 'words': ['كتلية']},
    'ج زء ف ي ا ل م ل ي و ن': {'domain': 'كيميائي', 'region': 'PPM', 'words': ['مليون']},
    'ت خ ف ي ف': {'domain': 'كيميائي', 'region': 'DILUTION', 'words': ['تخفيف']},
    'م ز ج': {'domain': 'كيميائي', 'region': 'MIXING', 'words': ['مزج']},
    'ت ح ر ي ك': {'domain': 'كيميائي', 'region': 'STIRRING', 'words': ['تحريك']},
    'ت س خ ي ن': {'domain': 'كيميائي', 'region': 'HEATING', 'words': ['تسخين']},
    'ت ب ر ي د': {'domain': 'كيميائي', 'region': 'COOLING', 'words': ['تبريد']},
    'ت ج ف ي ف': {'domain': 'كيميائي', 'region': 'DRYING', 'words': ['تجفيف']},
    'ت ر و ي ب': {'domain': 'كيميائي', 'region': 'DISTURBANCE', 'words': ['ترويب']},
    'ت ص ف ي ة': {'domain': 'كيميائي', 'region': 'PURIFICATION', 'words': ['تصفية']},
    'ت ب ل و ر': {'domain': 'كيميائي', 'region': 'CRYSTALLIZATION', 'words': ['تبلور']},
    'ت س م ي د': {'domain': 'كيميائي', 'region': 'FERTILIZATION', 'words': ['تسميد']},
    'ت خ م ي ر': {'domain': 'كيميائي', 'region': 'FERMENTATION', 'words': ['تخمر']},
    'ت ق ط ي ر': {'domain': 'كيميائي', 'region': 'DISTILLATION', 'words': ['تقطير']},
    'ت ص ع ي د': {'domain': 'كيميائي', 'region': 'SUBLIMATION', 'words': ['تصعيد']},
    'ك ث ا ف ة': {'domain': 'كيميائي', 'region': 'DENSITY', 'words': ['كثافة']},
    'ل ز و ج ة': {'domain': 'كيميائي', 'region': 'VISCOSITY', 'words': ['لزوجة']},
    'ت و ت ر س ط ح ي': {'domain': 'كيميائي', 'region': 'SURFACE_TENSION', 'words': ['سطحي']},
    'ش ع ر ي ة': {'domain': 'كيميائي', 'region': 'CAPILLARITY', 'words': ['شعرية']},
    'ت ن ا ض ح': {'domain': 'كيميائي', 'region': 'OSMOSIS', 'words': ['تنادح']},
    'ض غ ط أ س م و ز ي': {'domain': 'كيميائي', 'region': 'OSMOTIC_PRESSURE', 'words': ['أزموزي']},
    'غ ل ي ا ن': {'domain': 'كيميائي', 'region': 'BOILING', 'words': ['غليان']},
    'ت ج م د': {'domain': 'كيميائي', 'region': 'FREEZING', 'words': ['تجمد']},
    'ب خ ر': {'domain': 'كيميائي', 'region': 'EVAPORATION', 'words': ['بخار']},
    'ت ك ا ث ف': {'domain': 'كيميائي', 'region': 'CONDENSATION', 'words': ['تكاثف']},
    'ت س ا م ي': {'domain': 'كيميائي', 'region': 'SUBLIMATION', 'words': ['تسامي']},
    'ح ر ا ر ة ك ا م ن ة': {'domain': 'كيميائي', 'region': 'LATENT_HEAT', 'words': ['كامنة']},
    'ح ر ا ر ة ن و ع ي ة': {'domain': 'كيميائي', 'region': 'SPECIFIC_HEAT', 'words': ['نوعية']},
    'ت و ص ي ل ح ر ا ر ي': {'domain': 'كيميائي', 'region': 'THERMAL_CONDUCTIVITY', 'words': ['توصيل']},
    'ح م ل ح ر ا ر ي': {'domain': 'كيميائي', 'region': 'THERMAL_CONVECTION', 'words': ['حمل']},
    'إ ش ع ا ع ح ر ا ر ي': {'domain': 'كيميائي', 'region': 'THERMAL_RADIATION', 'words': ['إشعاع']},
    'ق ا ن و ن ف و ر ي ة': {'domain': 'كيميائي', 'region': 'FOURIER', 'words': ['فوريه']},
    'ق ا ن و ن ن ي و ت ن ت ب ر ي د': {'domain': 'كيميائي', 'region': 'NEWTON_COOLING', 'words': ['تبريد']},
    'ق ا ن و ن س ت ي ف ا ن ب و ل ت ز م ا ن': {'domain': 'كيميائي', 'region': 'STEFAN_BOLTZMANN', 'words': ['ستيفان']},
    'ق ا ن و ن ف ي ن إ ز ا ح ة': {'domain': 'كيميائي', 'region': 'WIEN_DISPLACEMENT', 'words': ['فين']},
    'ق ا ن و ن ب ل ا ن ك': {'domain': 'كيميائي', 'region': 'PLANCK', 'words': ['بلانك']},
    'ج س م أ س و د': {'domain': 'كيميائي', 'region': 'BLACK_BODY', 'words': ['أسود']},
    'ك م ض و ئ ي': {'domain': 'كيميائي', 'region': 'PHOTON', 'words': ['كمي']},
    'إ ز د و ا ج ي ة م و ج ة ج س ي م': {'domain': 'كيميائي', 'region': 'WAVE_PARTICLE', 'words': ['ازدواجية']},
    'ت ج ر ب ة ش ق ي ي و ن غ': {'domain': 'كيميائي', 'region': 'YOUNG_SLITS', 'words': ['يونغ']},
    'م ب د أ ت ك ا ف ؤ': {'domain': 'كيميائي', 'region': 'EQUIVALENCE', 'words': ['تكافؤ']},
    'ا ن ح ن اء ز م ك ا ن': {'domain': 'كيميائي', 'region': 'SPACETIME', 'words': ['زمكان']},
    'م ت ر ي ة ش و ا ر ز ش ي ل د': {'domain': 'كيميائي', 'region': 'SCHWARZSCHILD', 'words': ['شوارزشيلد']},
    'م ت ر ي ة ك ي ر': {'domain': 'كيميائي', 'region': 'KERR', 'words': ['كير']},
    'م ت ر ي ة ف ر ي د م ا ن': {'domain': 'كيميائي', 'region': 'FRIEDMANN', 'words': ['فريدمان']},
    'م ع ا د ل ة ف ر ي د م ا ن': {'domain': 'كيميائي', 'region': 'FRIEDMANN_EQUATION', 'words': ['فريدمان']},
    'ث ا ب ت ه ا ب ل': {'domain': 'كيميائي', 'region': 'HUBBLE_CONSTANT', 'words': ['هابل']},
    'ق ا ن و ن ه ا ب ل': {'domain': 'كيميائي', 'region': 'HUBBLE_LAW', 'words': ['هابل']},
    'ا ن ز ي ا ح أ ح م ر': {'domain': 'كيميائي', 'region': 'REDSHIFT', 'words': ['أحمر']},
    'ا ن ز ي ا ح أ ز ر ق': {'domain': 'كيميائي', 'region': 'BLUESHIFT', 'words': ['أزرق']},
    'إ ش ع ا ع خ ل ف ي ة ك و ن ي ة': {'domain': 'كيميائي', 'region': 'CMB', 'words': ['خلفية']},
    'م ا د ة م ظ ل م ة': {'domain': 'كيميائي', 'region': 'DARK_MATTER', 'words': ['مظلمة']},
    'ط ا ق ة م ظ ل م ة': {'domain': 'كيميائي', 'region': 'DARK_ENERGY', 'words': ['مظلمة']},
    'ث ق ب أ س و د': {'domain': 'كيميائي', 'region': 'BLACK_HOLE', 'words': ['أسود']},
    'ن ج م ن ي و ت ر و ن ي': {'domain': 'كيميائي', 'region': 'NEUTRON_STAR', 'words': ['نيوتروني']},
    'ن ج م': {'domain': 'كيميائي', 'region': 'STAR', 'words': ['نجم']},
    'ك و ك ب': {'domain': 'كيميائي', 'region': 'PLANET', 'words': ['كوكب']},
    'ق م ر': {'domain': 'كيميائي', 'region': 'MOON', 'words': ['قمر']},
    'م ج ر ة': {'domain': 'كيميائي', 'region': 'GALAXY', 'words': ['مجرة']},
    'ك و ن': {'domain': 'كيميائي', 'region': 'UNIVERSE', 'words': ['كون']},
    'ا ن ف ج ا ر ع ظ ي م': {'domain': 'كيميائي', 'region': 'BIG_BANG', 'words': ['عظيم']},
    'ت و س ع ك و ن': {'domain': 'كيميائي', 'region': 'EXPANSION', 'words': ['توسع']},
    'ن س ب ي ة ع ا م ة': {'domain': 'كيميائي', 'region': 'GENERAL_RELATIVITY', 'words': ['عامة']},
    'ن س ب ي ة خ ا ص ة': {'domain': 'كيميائي', 'region': 'SPECIAL_RELATIVITY', 'words': ['خاصة']},
    'م ي ك ا ن ي ك ا ك م': {'domain': 'كيميائي', 'region': 'QUANTUM_MECHANICS', 'words': ['كم']},
    'ن ظ ر ي ة أ و ت ا ر': {'domain': 'كيميائي', 'region': 'STRING_THEORY', 'words': ['أوتار']},
    'ج ا ذ ب ي ة ك م و م ي ة': {'domain': 'كيميائي', 'region': 'QUANTUM_GRAVITY', 'words': ['كمومية']},
    'ت ر ا ك ب ك م و م ي': {'domain': 'كيميائي', 'region': 'SUPERPOSITION', 'words': ['تراكب']},
    'ت ش ا ب ك ك م و م ي': {'domain': 'كيميائي', 'region': 'ENTANGLEMENT', 'words': ['تشابك']},
    'ن ف ق ك م و م ي': {'domain': 'كيميائي', 'region': 'TUNNELING', 'words': ['نفق']},
    'م ب د أ ع د م ي ق ي ن': {'domain': 'كيميائي', 'region': 'UNCERTAINTY', 'words': ['يقين']},
    'م ع ا د ل ة ش ر و د ن غ ر': {'domain': 'كيميائي', 'region': 'SCHRODINGER', 'words': ['شرودنغر']},
    'د ا ل ة م و ج ي ة': {'domain': 'كيميائي', 'region': 'WAVE_FUNCTION', 'words': ['موجية']},
    'ه ا م ل ت و ن ي': {'domain': 'كيميائي', 'region': 'HAMILTONIAN', 'words': ['هاملتوني']},
    'ل ا غ ر ا ن ج ي': {'domain': 'كيميائي', 'region': 'LAGRANGIAN', 'words': ['لاغرانجي']},
    'م ع ا د ل ة م ا ك س و ي ل': {'domain': 'كيميائي', 'region': 'MAXWELL', 'words': ['ماكسويل']},
    'م ع ا د ل ة ن ي و ت ن': {'domain': 'كيميائي', 'region': 'NEWTON', 'words': ['نيوتن']},
    'ق ا ن و ن ك ب ل ر': {'domain': 'كيميائي', 'region': 'KEPLER', 'words': ['كيبلر']},
    'ق ا ن و ن ب و ي ل': {'domain': 'كيميائي', 'region': 'BOYLE', 'words': ['بويل']},
    'ق ا ن و ن ش ا ر ل': {'domain': 'كيميائي', 'region': 'CHARLES', 'words': ['شارل']},
    'ق ا ن و ن أ و م': {'domain': 'كيميائي', 'region': 'OHM', 'words': ['أوم']},
    'ق ا ن و ن ف ا ر ا د ا ي': {'domain': 'كيميائي', 'region': 'FARADAY', 'words': ['فاراداي']},
    'ق ا ن و ن ل ي ن ز': {'domain': 'كيميائي', 'region': 'LENZ', 'words': ['لينز']},
    'ق ا ن و ن ك و ل و م': {'domain': 'كيميائي', 'region': 'COULOMB', 'words': ['كولوم']},
    'ق ا ن و ن غ ا و س': {'domain': 'كيميائي', 'region': 'GAUSS', 'words': ['غاوس']},
    'ق ا ن و ن أ م ب ي ر': {'domain': 'كيميائي', 'region': 'AMPERE', 'words': ['أمبير']},
    'ق ا ن و ن ب ي و ت س ا ف ا ر': {'domain': 'كيميائي', 'region': 'BIOT_SAVART', 'words': ['بيوت']},
    'ق ا ن و ن س ن ل': {'domain': 'كيميائي', 'region': 'SNELL', 'words': ['سنل']},
    'ق ا ن و ن ه و ك': {'domain': 'كيميائي', 'region': 'HOOKE', 'words': ['هوك']},
    'ق ا ن و ن ن ي و ت ن ج ا ذ ب ي ة': {'domain': 'كيميائي', 'region': 'NEWTON_GRAVITY', 'words': ['جاذبية']},
    'ق ا ن و ن ح ف ظ ط ا ق ة': {'domain': 'كيميائي', 'region': 'ENERGY_CONSERVATION', 'words': ['حفظ']},
    'ق ا ن و ن ح ف ظ ز خ م': {'domain': 'كيميائي', 'region': 'MOMENTUM_CONSERVATION', 'words': ['زخم']},
    'ق ا ن و ن ح ف ظ ش ح ن ة': {'domain': 'كيميائي', 'region': 'CHARGE_CONSERVATION', 'words': ['شحنة']},
    'ق ا ن و ن ح ف ظ ك ت ل ة': {'domain': 'كيميائي', 'region': 'MASS_CONSERVATION', 'words': ['كتلة']},
    'ق ا ن و ن د ي ن ا م ي ك ا ح ر ا ر ي ة أ و ل': {'domain': 'كيميائي', 'region': 'FIRST_LAW_THERMO', 'words': ['أول']},
    'ق ا ن و ن د ي ن ا م ي ك ا ح ر ا ر ي ة ث ا ن ي': {'domain': 'كيميائي', 'region': 'SECOND_LAW_THERMO', 'words': ['ثاني']},
    'ق ا ن و ن د ي ن ا م ي ك ا ح ر ا ر ي ة ث ا ل ث': {'domain': 'كيميائي', 'region': 'THIRD_LAW_THERMO', 'words': ['ثالث']},
    'إ ن ت ر و ب ي ا': {'domain': 'كيميائي', 'region': 'ENTROPY', 'words': ['إنتروبي']},
    'إ ن ث ا ل ب ي': {'domain': 'كيميائي', 'region': 'ENTHALPY', 'words': ['إنثالبى']},
    'ط ا ق ة ح ر ة': {'domain': 'كيميائي', 'region': 'FREE_ENERGY', 'words': ['حرة']},
    'ط ا ق ة ج ي ب س': {'domain': 'كيميائي', 'region': 'GIBBS', 'words': ['جيبس']},
    'ط ا ق ة ه ل م ه و ل ت ز': {'domain': 'كيميائي', 'region': 'HELMHOLTZ', 'words': ['هلمهولتز']},
    'ك م و ن ك ي م ي ا و ي': {'domain': 'كيميائي', 'region': 'CHEMICAL_POTENTIAL', 'words': ['كمون']},
    'ن ش ا ط ك ي م ي ا و ي': {'domain': 'كيميائي', 'region': 'CHEMICAL_ACTIVITY', 'words': ['نشاط']},
    'م ع ا د ل ة ح ا ل ة': {'domain': 'كيميائي', 'region': 'EQUATION_OF_STATE', 'words': ['حالة']},
    'ق ا ن و ن غ ا ز م ث ا ل ي': {'domain': 'كيميائي', 'region': 'IDEAL_GAS', 'words': ['مثالي']},
    'ث ا ب ت غ ا ز': {'domain': 'كيميائي', 'region': 'GAS_CONSTANT', 'words': ['غاز']},
    'ح ج م م و ل ي': {'domain': 'كيميائي', 'region': 'MOLAR_VOLUME', 'words': ['مولي']},
    'ك ت ل ة م و ل ي ة': {'domain': 'كيميائي', 'region': 'MOLAR_MASS', 'words': ['مولية']},
    'ت ر ك ي ز م و ل ي': {'domain': 'كيميائي', 'region': 'MOLAR_CONCENTRATION', 'words': ['مولي']},
    'م و ل ا ر ي ة': {'domain': 'كيميائي', 'region': 'MOLARITY', 'words': ['مولارية']},
    'م و ل ا ل ي ة': {'domain': 'كيميائي', 'region': 'MOLALITY', 'words': ['مولالية']},
    'ك س ر م و ل ي': {'domain': 'كيميائي', 'region': 'MOLE_FRACTION', 'words': ['مولي']},
    'ق ا ن و ن ر ا ؤ ل ت': {'domain': 'كيميائي', 'region': 'RAOULT', 'words': ['راؤول']},
    'ق ا ن و ن ه ن ر ي': {'domain': 'كيميائي', 'region': 'HENRY', 'words': ['هنري']},
    'ت و ا ز ن ط و ر ي': {'domain': 'كيميائي', 'region': 'PHASE_EQUILIBRIUM', 'words': ['طوري']},
    'م خ ط ط ط و ر ي': {'domain': 'كيميائي', 'region': 'PHASE_DIAGRAM', 'words': ['مخطط']},
    'ن ق ط ة ح ر ج ة': {'domain': 'كيميائي', 'region': 'CRITICAL_POINT', 'words': ['حرجة']},
    'ن ق ط ة ث ل ا ث ي ة': {'domain': 'كيميائي', 'region': 'TRIPLE_POINT', 'words': ['ثلاثية']},
    'ت س ا م ي': {'domain': 'كيميائي', 'region': 'SUBLIMATION', 'words': ['تسامي']},
    'ت ك ا ث ف': {'domain': 'كيميائي', 'region': 'CONDENSATION', 'words': ['تكاثف']},
    'ت ب خ ر': {'domain': 'كيميائي', 'region': 'EVAPORATION', 'words': ['تبخر']},
    'غ ل ي ا ن': {'domain': 'كيميائي', 'region': 'BOILING', 'words': ['غليان']},
    'ا ن ص ه ا ر': {'domain': 'كيميائي', 'region': 'MELTING', 'words': ['انصهار']},
    'ت ج م د': {'domain': 'كيميائي', 'region': 'FREEZING', 'words': ['تجمد']},
    'ح ر ا ر ة ا ن ص ه ا ر': {'domain': 'كيميائي', 'region': 'HEAT_OF_FUSION', 'words': ['انصهار']},
    'ح ر ا ر ة ت ب خ ر': {'domain': 'كيميائي', 'region': 'HEAT_OF_VAPORIZATION', 'words': ['تبخر']},
    'س ع ة ح ر ا ر ي ة': {'domain': 'كيميائي', 'region': 'HEAT_CAPACITY', 'words': ['سعة']},
    'س ع ة ح ر ا ر ي ة ن و ع ي ة': {'domain': 'كيميائي', 'region': 'SPECIFIC_HEAT', 'words': ['نوعية']},
    'ت و ص ي ل ح ر ا ر ي': {'domain': 'كيميائي', 'region': 'THERMAL_CONDUCTIVITY', 'words': ['توصيل']},
    'ح م ل ح ر ا ر ي': {'domain': 'كيميائي', 'region': 'THERMAL_CONVECTION', 'words': ['حمل']},
    'إ ش ع ا ع ح ر ا ر ي': {'domain': 'كيميائي', 'region': 'THERMAL_RADIATION', 'words': ['إشعاع']},
    'ق ا ن و ن س ت ي ف ا ن ب و ل ت ز م ا ن': {'domain': 'كيميائي', 'region': 'STEFAN_BOLTZMANN', 'words': ['ستيفان']},
    'ق ا ن و ن ف ي ن': {'domain': 'كيميائي', 'region': 'WIEN', 'words': ['فين']},
    'ق ا ن و ن ب ل ا ن ك': {'domain': 'كيميائي', 'region': 'PLANCK', 'words': ['بلانك']},
    'ج س م أ س و د': {'domain': 'كيميائي', 'region': 'BLACK_BODY', 'words': ['أسود']},
    'إ ش ع ا ع ج س م أ س و د': {'domain': 'كيميائي', 'region': 'BLACK_BODY_RADIATION', 'words': ['أسود']},
    'ك م ض و ئ ي': {'domain': 'كيميائي', 'region': 'PHOTON', 'words': ['كمي']},
    'إ ز د و ا ج ي ة م و ج ة ج س ي م': {'domain': 'كيميائي', 'region': 'WAVE_PARTICLE', 'words': ['ازدواجية']},
    'ت ج ر ب ة ش ق ي ي ي و ن غ': {'domain': 'كيميائي', 'region': 'YOUNG', 'words': ['يونغ']},
    'م ب د أ ت ك ا ف ؤ': {'domain': 'كيميائي', 'region': 'EQUIVALENCE', 'words': ['تكافؤ']},
    'ا ن ح ن ا ء ز م ك ا ن': {'domain': 'كيميائي', 'region': 'SPACETIME', 'words': ['زمكان']},
    'م ت ر ي ة ش و ا ر ز ش ي ل د': {'domain': 'كيميائي', 'region': 'SCHWARZSCHILD', 'words': ['شوارزشيلد']},
    'م ت ر ي ة ك ي ر': {'domain': 'كيميائي', 'region': 'KERR', 'words': ['كير']},
    'م ت ر ي ة ف ر ي د م ا ن': {'domain': 'كيميائي', 'region': 'FRIEDMANN', 'words': ['فريدمان']},
    'م ع ا د ل ة ف ر ي د م ا ن': {'domain': 'كيميائي', 'region': 'FRIEDMANN_EQUATIONS', 'words': ['فريدمان']},
    'ث ا ب ت ه ا ب ل': {'domain': 'كيميائي', 'region': 'HUBBLE_CONSTANT', 'words': ['هابل']},
    'ق ا ن و ن ه ا ب ل': {'domain': 'كيميائي', 'region': 'HUBBLE_LAW', 'words': ['هابل']},
    'ا ن ز ي ا ح أ ح م ر': {'domain': 'كيميائي', 'region': 'REDSHIFT', 'words': ['أحمر']},
    'ا ن ز ي ا ح أ ز ر ق': {'domain': 'كيميائي', 'region': 'BLUESHIFT', 'words': ['أزرق']},
    'إ ش ع ا ع خ ل ف ي ة ك و ن ي ة': {'domain': 'كيميائي', 'region': 'CMB', 'words': ['خلفية']},
    'CMB': {'domain': 'كيميائي', 'region': 'CMB_SHORT', 'words': ['CMB']},
    'م ا د ة ب ا ر د ة': {'domain': 'كيميائي', 'region': 'COLD_MATTER', 'words': ['باردة']},
}
def get_total_roots_count():
    """إرجاع العدد الإجمالي للجذور"""
    return len(EXPANDED_ROOTS)
def get_roots_by_domain(domain: str) -> Dict:
    """إرجاع جميع الجذور في مجال معين"""
    return {k: v for k, v in EXPANDED_ROOTS.items() if v['domain'] == domain}
def get_all_words() -> List[str]:
    """إرجاع جميع الكلمات من جميع الجذور"""
    words = []
    for root_data in EXPANDED_ROOTS.values():
        words.extend(root_data['words'])
    return words
if __name__ == "__main__":
    print(f"📊 إجمالي الجذور: {get_total_roots_count()}")
    print(f"📊 إجمالي الكلمات: {len(get_all_words())}")
    domains = set(v['domain'] for v in EXPANDED_ROOTS.values())
    print(f"\n📚 المجالات المغطاة: {len(domains)}")
    for domain in sorted(domains):
        count = len(get_roots_by_domain(domain))
        print(f"   🔹 {domain}: {count} جذر")
